# Shared helpers for serving the writeup (site/) from the home server.
#
# Windows PowerShell 5.1. Mirrors the conventions the other sites on this host
# use (C:\ProgramData\Portfolio and friends): runtime state under
# C:\ProgramData\<Name>, separate from any source checkout; immutable release
# directories; one marker-delimited `import` line in the host's main Caddyfile;
# `caddy validate` then `caddy reload`, with both files restored if either
# fails.
#
# Where this differs from Portfolio, it is because the site is static. The page
# is prerendered by `next build` with `output: 'export'`, so there is no Node
# process to start, health-check, keep on a second port or stop -- Caddy serves
# the release directory straight off disk, and a release switch is a Caddyfile
# rewrite plus a reload.
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$script:SiteHost = 'sgemm.ethanyanxu.com'
$script:Marker = 'BareMetalBard'
$script:RepoUrl = 'https://github.com/OoEthanoO/bare-metal-bard.git'
# What a deploy is keyed on: the last commit that changed the site or these
# scripts. Most commits to this repo touch kernels and benchmarks only, and
# rebuilding an unchanged page for each of them would be all cost.
$script:DeployPaths = @('site', 'deploy/windows')

function Assert-Administrator {
    $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { throw 'Administrator access is required.' }
}
function Read-Json([string]$Path) {
    if (Test-Path -LiteralPath $Path) { return Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json }
    return $null
}
function Write-Json([string]$Path, $Value) {
    $temporary = $Path + '.new'
    [IO.File]::WriteAllText($temporary, ($Value | ConvertTo-Json -Depth 8), (New-Object Text.UTF8Encoding $false))
    if (Test-Path -LiteralPath $Path) { [IO.File]::Replace($temporary, $Path, [NullString]::Value) }
    else { [IO.File]::Move($temporary, $Path) }
}
function Assert-UnderRoot([string]$Path, [string]$Root) {
    $resolved = [IO.Path]::GetFullPath($Path)
    $prefix = [IO.Path]::GetFullPath($Root).TrimEnd('\') + '\'
    if (-not $resolved.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) { throw "Path outside runtime root: $resolved" }
    return $resolved
}
function Invoke-Tool([string]$File, [string[]]$Arguments, [string]$Log) {
    $old = $ErrorActionPreference
    try {
        $ErrorActionPreference = 'Continue'
        & $File @Arguments >> $Log 2>&1
        $code = $LASTEXITCODE
    } finally { $ErrorActionPreference = $old }
    if ($code -ne 0) { throw "Tool failed ($code): $(Split-Path -Leaf $File) $($Arguments -join ' '). See $Log" }
}

# A release is checkable on disk before any traffic reaches it: the page, the
# 404 page, and a version stamp naming the commit it was built from.
function Test-ReleaseFiles($State) {
    $www = Join-Path $State.release 'www'
    foreach ($f in 'index.html', '404.html', 'version.txt') {
        if (-not (Test-Path -LiteralPath (Join-Path $www $f))) { return $false }
    }
    return ([IO.File]::ReadAllText((Join-Path $www 'version.txt')).Trim() -eq $State.commit)
}

# What visitors get, asked of Caddy itself over loopback with real TLS. --resolve
# pins the name to 127.0.0.1 so the router and public DNS are not involved;
# --ssl-no-revoke because Schannel's revocation check can fail on a machine
# that is otherwise fine, and that is not what this is testing.
function Test-Served([string]$Commit, [int]$Seconds = 20) {
    $deadline = (Get-Date).AddSeconds($Seconds)
    do {
        $old = $ErrorActionPreference
        try {
            $ErrorActionPreference = 'Continue'
            $body = & curl.exe -s --ssl-no-revoke --max-time 10 --resolve ($script:SiteHost + ':443:127.0.0.1') ('https://' + $script:SiteHost + '/version.txt') 2>$null
            $code = $LASTEXITCODE
        } finally { $ErrorActionPreference = $old }
        if ($code -eq 0 -and $body -and ($body | Out-String).Trim() -eq $Commit) { return $true }
        Start-Sleep -Seconds 3
    } while ((Get-Date) -lt $deadline)
    return $false
}

function Get-SiteBlock([string]$Root, $State) {
    $www = (Join-Path $State.release 'www') -replace '\\', '/'
    $static = (Join-Path $Root 'static') -replace '\\', '/'
    $log = (Join-Path $Root 'logs\access.log') -replace '\\', '/'
    return @"
# Generated by deploy/windows in bare-metal-bard. Serving $($State.commit).
$($script:SiteHost) {
    encode zstd gzip
    header X-BareMetalBard-Host finprint-host

    # Content-hashed build assets from EVERY release, so a visitor whose tab
    # spans a release switch can still fetch the chunks its old HTML names.
    handle_path /_next/static/* {
        root * "$static"
        header Cache-Control "public, max-age=31536000, immutable"
        file_server
    }
    handle {
        root * "$www"
        file_server
    }
    handle_errors 404 {
        root * "$www"
        rewrite * /404.html
        file_server
    }
    log {
        output file "$log" {
            roll_size 10MB
            roll_keep 3
        }
    }
}
"@
}

function Switch-Caddy([string]$Root, $Config, $State) {
    $null = Assert-UnderRoot $State.release (Join-Path $Root 'releases')
    if (-not (Test-ReleaseFiles $State)) { throw 'Release files are incomplete; Caddy was not changed.' }
    $sitePath = Join-Path $Root 'Caddyfile'
    $oldSite = if (Test-Path -LiteralPath $sitePath) { [IO.File]::ReadAllText($sitePath) } else { $null }
    $oldMain = [IO.File]::ReadAllText($Config.mainCaddyfile)
    $log = Join-Path $Root 'logs\caddy-reload.log'
    $utf8 = New-Object Text.UTF8Encoding $false
    $begin = "# BEGIN $($script:Marker) (managed)"
    $nextMain = $oldMain
    if (-not $oldMain.Contains($begin)) {
        $import = $sitePath -replace '\\', '/'
        $nextMain = $oldMain.TrimEnd() + "`r`n`r`n$begin`r`nimport $import`r`n# END $($script:Marker) (managed)`r`n"
    }
    try {
        if ($oldMain -ne $nextMain) {
            Copy-Item -LiteralPath $Config.mainCaddyfile -Destination (Join-Path $Root ('logs\Caddyfile-before-' + (Get-Date -Format 'yyyyMMddHHmmss')))
            [IO.File]::WriteAllText($Config.mainCaddyfile, $nextMain, $utf8)
        }
        [IO.File]::WriteAllText($sitePath, (Get-SiteBlock $Root $State), $utf8)
        Invoke-Tool $Config.caddy @('validate', '--config', $Config.mainCaddyfile, '--adapter', 'caddyfile') $log
        Invoke-Tool $Config.caddy @('reload', '--config', $Config.mainCaddyfile, '--adapter', 'caddyfile') $log
    } catch {
        if ([IO.File]::ReadAllText($Config.mainCaddyfile) -eq $nextMain -and $oldMain -ne $nextMain) {
            [IO.File]::WriteAllText($Config.mainCaddyfile, $oldMain, $utf8)
        }
        if ($null -ne $oldSite) { [IO.File]::WriteAllText($sitePath, $oldSite, $utf8) }
        elseif (Test-Path -LiteralPath $sitePath) { Remove-Item -LiteralPath $sitePath -Force }
        try { Invoke-Tool $Config.caddy @('reload', '--config', $Config.mainCaddyfile, '--adapter', 'caddyfile') $log } catch {}
        throw
    }
}

# Keep the newest few releases, and never one that a state file still names --
# the active one, the one rollback would return to, or a prepared one.
function Remove-OldReleases([string]$Root, [int]$Keep = 5) {
    $named = @('active.json', 'previous.json', 'prepared.json') | ForEach-Object {
        $s = Read-Json (Join-Path $Root $_); if ($s) { [IO.Path]::GetFullPath($s.release).TrimEnd('\') }
    }
    # Release names are <commit>-<yyyyMMddHHmmss>; sort on the timestamp, since
    # sorting the whole name would order them by commit hash, not by age.
    $all = @(Get-ChildItem -LiteralPath (Join-Path $Root 'releases') -Directory |
        Sort-Object { ($_.Name -split '-')[-1] } -Descending)
    foreach ($dir in ($all | Select-Object -Skip $Keep)) {
        $full = [IO.Path]::GetFullPath($dir.FullName).TrimEnd('\')
        if ($named -notcontains $full) { Remove-Item -LiteralPath $full -Recurse -Force }
    }
}
