#!/usr/bin/env python3
"""Generate site/app/data.ts from the actual benchmark CSV and training log.

Every number on the writeup page comes from a measured run rather than being
typed in by hand, so the page cannot drift from the results.

usage: python3 tools/make_site_data.py
"""
import csv
import json
import os
import re
from collections import defaultdict

CSV = "bench/results.csv"
CSV_TF32 = "bench/results_tf32.csv"
LOG = "bench/logs/train_final.log"
OUT = "site/app/data.ts"

NOTES = {
    "naive": "one thread per output element, uncoalesced",
    "coalesced": "swapped which index maps to threadIdx.x",
    "smem": "32x32 shared-memory tile",
    "tile1d": "8 outputs per thread (TM=8)",
    "tile2d": "8x8 register tile, outer-product form",
    "vectorized": "float4 loads + transposed A tile",
    "warptile": "block -> warp -> thread blocking",
    "dbuffer": "double-buffered SMEM, one barrier per chunk",
    "tensorcore": "WMMA m16n16k8 TF32 tensor cores",
}
INTENSITY = {
    "naive": 0.25, "coalesced": 0.25, "smem": 8, "tile1d": 16,
    "tile2d": 32, "vectorized": 32, "warptile": 32, "dbuffer": 32,
    "tensorcore": 64,
}

# ---- benchmark ----
rows, order, cublas = defaultdict(dict), [], {}
with open(CSV) as f:
    for r in csv.DictReader(f):
        name, size = r["kernel"], int(r["size"])
        if name not in order:
            order.append(name)
        rows[name][size] = (float(r["gflops_best"]), float(r["pct_of_cublas"]))
        cublas[size] = float(r["cublas_gflops_best"])

BIG = max(cublas)
kernels = []
for i, name in enumerate(order):
    gf, pct = rows[name][BIG]
    kernels.append({
        "id": i + 1, "name": name, "gflops": gf, "pct": pct,
        "note": NOTES.get(name, ""), "intensity": INTENSITY.get(name, 0),
        "bySize": {str(s): rows[name][s][1] for s in sorted(rows[name])},
    })

# ---- TF32 comparison ----
# cuBLAS SGEMM defaults to true fp32; TF32 is opt-in. Carrying both baselines
# keeps the tensor-core kernel's numbers honest: it beats fp32 cuBLAS but
# trails cuBLAS's own tensor-core path.
tf32 = {}
if os.path.exists(CSV_TF32):
    with open(CSV_TF32) as f:
        for r in csv.DictReader(f):
            tf32.setdefault(r["kernel"], {})[r["size"]] = {
                "gflops": float(r["gflops_best"]),
                "pct": float(r["pct_of_cublas"]),
                "cublasTf32": float(r["cublas_gflops_best"]),
            }

# ---- training ----
train, evals = [], []
step_re = re.compile(r"^step\s+(\d+)/(\d+)\s+loss\s+([\d.]+).*?([\d.]+) ms\s+(\d+) tok/s\s+(\d+) GFLOP/s")
eval_re = re.compile(r"\[eval\]\s+step\s+(\d+)\s+val loss\s+([\d.]+)")
total_steps = 0
text = open(LOG).read() if os.path.exists(LOG) else ""
for ln in text.splitlines():
    m = step_re.match(ln)
    if m:
        total_steps = int(m.group(2))
        train.append({"step": int(m.group(1)), "loss": float(m.group(3)),
                      "ms": float(m.group(4)), "tok": int(m.group(5)),
                      "gflops": int(m.group(6))})
    m = eval_re.search(ln)
    if m:
        evals.append({"step": int(m.group(1)), "loss": float(m.group(2))})

best = min(evals, key=lambda e: e["loss"]) if evals else {"step": 0, "loss": 0}
med = lambda xs: sorted(xs)[len(xs) // 2] if xs else 0

# Prefer the sample generated from the BEST-validation checkpoint. The sample
# printed at the end of training comes from the final (overfit) weights, which
# is not the model worth showing.
sample = ""
if os.path.exists("bench/logs/sample_best.txt"):
    s = open("bench/logs/sample_best.txt").read()
    j = s.find("\n\n")
    sample = (s[j:] if j >= 0 else s).strip()
if not sample:
    i = text.rfind("final sample:")
    if i >= 0:
        sample = text[i + len("final sample:"):].strip()

m_best = re.search(r"best\s+val loss\s+([\d.]+) at step (\d+)", text)
m_final = re.search(r"final\s+train loss\s+([\d.]+)\s+val loss\s+([\d.]+)", text)

training = {
    "totalSteps": total_steps,
    "bestVal": float(m_best.group(1)) if m_best else best["loss"],
    "bestStep": int(m_best.group(2)) if m_best else best["step"],
    "finalTrain": float(m_final.group(1)) if m_final else (train[-1]["loss"] if train else 0),
    "finalVal": float(m_final.group(2)) if m_final else 0,
    "msPerStep": med([t["ms"] for t in train]),
    "tokPerSec": med([t["tok"] for t in train]),
    "gflops": med([t["gflops"] for t in train]),
    "curve": [{"step": t["step"], "loss": t["loss"]} for t in train],
    "evals": evals,
    "sample": sample[:2600],
}

data = {
    "kernels": kernels,
    "tf32": tf32,
    "cublas": cublas[BIG],
    "benchSize": BIG,
    "sizes": sorted(cublas),
    "training": training,
}

hdr = ("// GENERATED by tools/make_site_data.py -- do not edit.\n"
       "// Numbers come from bench/results.csv and bench/logs/train_final.log.\n\n")
body = "export const data = " + json.dumps(data, indent=2) + " as const;\n"
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write(hdr + body)
print("wrote", OUT)
print("kernels: %d, best %s %.1f GF/s (%.1f%%)"
      % (len(kernels), kernels[-1]["name"], kernels[-1]["gflops"], kernels[-1]["pct"]))
print("training: %d steps, best val %.4f @ %d, %.0f tok/s"
      % (training["totalSteps"], training["bestVal"], training["bestStep"],
         training["tokPerSec"]))
