// GENERATED by tools/make_site_data.py -- do not edit.
// Numbers come from bench\results_5080.csv and bench\logs\train_5080_tf32.log.

export const data = {
  "kernels": [
    {
      "id": 1,
      "name": "naive",
      "gflops": 138.21,
      "pct": 1.13,
      "note": "one thread per output element, uncoalesced",
      "intensity": 0.25,
      "bySize": {
        "128": 16.02,
        "256": 5.55,
        "512": 2.9,
        "1024": 1.48,
        "1536": 1.26,
        "2048": 1.18,
        "4096": 1.13,
        "6144": 1.19
      }
    },
    {
      "id": 2,
      "name": "coalesced",
      "gflops": 900.99,
      "pct": 7.39,
      "note": "swapped which index maps to threadIdx.x",
      "intensity": 0.25,
      "bySize": {
        "128": 89.64,
        "256": 38.61,
        "512": 21.65,
        "1024": 11.63,
        "1536": 9.95,
        "2048": 9.19,
        "4096": 7.39,
        "6144": 7.82
      }
    },
    {
      "id": 3,
      "name": "smem",
      "gflops": 1376.58,
      "pct": 11.31,
      "note": "32x32 shared-memory tile",
      "intensity": 8,
      "bySize": {
        "128": 111.11,
        "256": 49.23,
        "512": 28.48,
        "1024": 15.25,
        "1536": 13.29,
        "2048": 12.19,
        "4096": 11.31,
        "6144": 11.98
      }
    },
    {
      "id": 4,
      "name": "tile1d",
      "gflops": 4280.12,
      "pct": 35.16,
      "note": "8 outputs per thread (TM=8)",
      "intensity": 16,
      "bySize": {
        "128": 71.23,
        "256": 54.83,
        "512": 48.36,
        "1024": 39.47,
        "1536": 38.36,
        "2048": 35.53,
        "4096": 35.16,
        "6144": 37.42
      }
    },
    {
      "id": 5,
      "name": "tile2d",
      "gflops": 8412.35,
      "pct": 69.17,
      "note": "8x8 register tile, outer-product form",
      "intensity": 32,
      "bySize": {
        "128": 39.97,
        "256": 29.6,
        "512": 42.21,
        "1024": 51.17,
        "1536": 62.56,
        "2048": 62.97,
        "4096": 69.17,
        "6144": 74.94
      }
    },
    {
      "id": 6,
      "name": "vectorized",
      "gflops": 10217.67,
      "pct": 84.09,
      "note": "float4 loads + transposed A tile",
      "intensity": 32,
      "bySize": {
        "128": 47.5,
        "256": 34.34,
        "512": 46.44,
        "1024": 61.73,
        "1536": 71.57,
        "2048": 72.59,
        "4096": 84.09,
        "6144": 90.69
      }
    },
    {
      "id": 7,
      "name": "warptile",
      "gflops": 9640.43,
      "pct": 79.26,
      "note": "block -> warp -> thread blocking",
      "intensity": 32,
      "bySize": {
        "128": 39.42,
        "256": 31.35,
        "512": 44.77,
        "1024": 59.26,
        "1536": 56.72,
        "2048": 63.39,
        "4096": 79.26,
        "6144": 84.93
      }
    },
    {
      "id": 8,
      "name": "dbuffer",
      "gflops": 10604.75,
      "pct": 87.21,
      "note": "double-buffered SMEM, one barrier per chunk",
      "intensity": 32,
      "bySize": {
        "128": 43.64,
        "256": 34.3,
        "512": 49.94,
        "1024": 60.72,
        "1536": 59.01,
        "2048": 67.81,
        "4096": 87.21,
        "6144": 98.73
      }
    },
    {
      "id": 9,
      "name": "tensorcore",
      "gflops": 7875.08,
      "pct": 64.78,
      "note": "WMMA m16n16k8 TF32 tensor cores",
      "intensity": 64,
      "bySize": {
        "128": 45.11,
        "256": 32.31,
        "512": 44.21,
        "1024": 46.7,
        "1536": 59.76,
        "2048": 59.93,
        "4096": 64.78,
        "6144": 71.09
      }
    },
    {
      "id": 10,
      "name": "mma",
      "gflops": 14198.19,
      "pct": 116.62,
      "note": "raw mma.sync PTX, lane-major SMEM, 64x64 warp tile",
      "intensity": 64,
      "bySize": {
        "128": 50.04,
        "256": 42.32,
        "512": 63.5,
        "1024": 81.5,
        "1536": 102.33,
        "2048": 104.85,
        "4096": 116.62,
        "6144": 128.99
      }
    },
    {
      "id": 11,
      "name": "cpasync",
      "gflops": 15351.94,
      "pct": 126.26,
      "note": "cp.async staging pipeline, 64x64 warp tile",
      "intensity": 64,
      "bySize": {
        "128": 51.07,
        "256": 43.88,
        "512": 65.15,
        "1024": 83.86,
        "1536": 106.77,
        "2048": 109.74,
        "4096": 126.26,
        "6144": 136.36
      }
    }
  ],
  "tf32": {
    "tensorcore": {
      "1024": {
        "gflops": 6574.79,
        "pct": 74.93,
        "cublasTf32": 8811.56
      },
      "2048": {
        "gflops": 7420.26,
        "pct": 79.89,
        "cublasTf32": 9284.57
      },
      "4096": {
        "gflops": 8299.39,
        "pct": 78.74,
        "cublasTf32": 10544.25
      }
    },
    "mma": {
      "1024": {
        "gflops": 7108.99,
        "pct": 80.34,
        "cublasTf32": 8848.74
      },
      "2048": {
        "gflops": 8172.05,
        "pct": 87.87,
        "cublasTf32": 9305.17
      },
      "4096": {
        "gflops": 9191.74,
        "pct": 87.36,
        "cublasTf32": 10538.45
      }
    }
  },
  "cublas": 12157.92,
  "benchSize": 4096,
  "sizes": [
    128,
    256,
    512,
    1024,
    1536,
    2048,
    4096,
    6144
  ],
  "training": {
    "totalSteps": 5000,
    "bestVal": 1.5073,
    "bestStep": 2400,
    "finalTrain": 0.6519,
    "finalVal": 1.9675,
    "msPerStep": 25.4,
    "tokPerSec": 161123,
    "gflops": 11576,
    "curve": [
      {
        "step": 1,
        "loss": 4.2625
      },
      {
        "step": 10,
        "loss": 3.11
      },
      {
        "step": 20,
        "loss": 2.743
      },
      {
        "step": 30,
        "loss": 2.6151
      },
      {
        "step": 40,
        "loss": 2.5988
      },
      {
        "step": 50,
        "loss": 2.5339
      },
      {
        "step": 60,
        "loss": 2.5306
      },
      {
        "step": 70,
        "loss": 2.4766
      },
      {
        "step": 80,
        "loss": 2.4958
      },
      {
        "step": 90,
        "loss": 2.5092
      },
      {
        "step": 100,
        "loss": 2.4959
      },
      {
        "step": 110,
        "loss": 2.5246
      },
      {
        "step": 120,
        "loss": 2.4466
      },
      {
        "step": 130,
        "loss": 2.4271
      },
      {
        "step": 140,
        "loss": 2.4549
      },
      {
        "step": 150,
        "loss": 2.4169
      },
      {
        "step": 160,
        "loss": 2.41
      },
      {
        "step": 170,
        "loss": 2.4117
      },
      {
        "step": 180,
        "loss": 2.3989
      },
      {
        "step": 190,
        "loss": 2.3875
      },
      {
        "step": 200,
        "loss": 2.3848
      },
      {
        "step": 210,
        "loss": 2.3927
      },
      {
        "step": 220,
        "loss": 2.3132
      },
      {
        "step": 230,
        "loss": 2.2532
      },
      {
        "step": 240,
        "loss": 2.1849
      },
      {
        "step": 250,
        "loss": 2.1543
      },
      {
        "step": 260,
        "loss": 2.1048
      },
      {
        "step": 270,
        "loss": 2.1191
      },
      {
        "step": 280,
        "loss": 2.0818
      },
      {
        "step": 290,
        "loss": 2.0957
      },
      {
        "step": 300,
        "loss": 2.0298
      },
      {
        "step": 310,
        "loss": 2.019
      },
      {
        "step": 320,
        "loss": 2.0214
      },
      {
        "step": 330,
        "loss": 1.9736
      },
      {
        "step": 340,
        "loss": 1.9846
      },
      {
        "step": 350,
        "loss": 1.9233
      },
      {
        "step": 360,
        "loss": 1.8595
      },
      {
        "step": 370,
        "loss": 1.9353
      },
      {
        "step": 380,
        "loss": 1.8684
      },
      {
        "step": 390,
        "loss": 1.8098
      },
      {
        "step": 400,
        "loss": 1.883
      },
      {
        "step": 410,
        "loss": 1.8062
      },
      {
        "step": 420,
        "loss": 1.8232
      },
      {
        "step": 430,
        "loss": 1.8834
      },
      {
        "step": 440,
        "loss": 1.8388
      },
      {
        "step": 450,
        "loss": 1.8452
      },
      {
        "step": 460,
        "loss": 1.7938
      },
      {
        "step": 470,
        "loss": 1.7514
      },
      {
        "step": 480,
        "loss": 1.7961
      },
      {
        "step": 490,
        "loss": 1.6851
      },
      {
        "step": 500,
        "loss": 1.7484
      },
      {
        "step": 510,
        "loss": 1.7106
      },
      {
        "step": 520,
        "loss": 1.6497
      },
      {
        "step": 530,
        "loss": 1.6794
      },
      {
        "step": 540,
        "loss": 1.7688
      },
      {
        "step": 550,
        "loss": 1.6778
      },
      {
        "step": 560,
        "loss": 1.7597
      },
      {
        "step": 570,
        "loss": 1.6709
      },
      {
        "step": 580,
        "loss": 1.6413
      },
      {
        "step": 590,
        "loss": 1.7257
      },
      {
        "step": 600,
        "loss": 1.6436
      },
      {
        "step": 610,
        "loss": 1.6718
      },
      {
        "step": 620,
        "loss": 1.6169
      },
      {
        "step": 630,
        "loss": 1.5704
      },
      {
        "step": 640,
        "loss": 1.6943
      },
      {
        "step": 650,
        "loss": 1.6105
      },
      {
        "step": 660,
        "loss": 1.5669
      },
      {
        "step": 670,
        "loss": 1.6323
      },
      {
        "step": 680,
        "loss": 1.6472
      },
      {
        "step": 690,
        "loss": 1.5575
      },
      {
        "step": 700,
        "loss": 1.5737
      },
      {
        "step": 710,
        "loss": 1.5561
      },
      {
        "step": 720,
        "loss": 1.5999
      },
      {
        "step": 730,
        "loss": 1.6126
      },
      {
        "step": 740,
        "loss": 1.5955
      },
      {
        "step": 750,
        "loss": 1.6004
      },
      {
        "step": 760,
        "loss": 1.5718
      },
      {
        "step": 770,
        "loss": 1.5283
      },
      {
        "step": 780,
        "loss": 1.6114
      },
      {
        "step": 790,
        "loss": 1.5179
      },
      {
        "step": 800,
        "loss": 1.5215
      },
      {
        "step": 810,
        "loss": 1.5995
      },
      {
        "step": 820,
        "loss": 1.5052
      },
      {
        "step": 830,
        "loss": 1.5536
      },
      {
        "step": 840,
        "loss": 1.5732
      },
      {
        "step": 850,
        "loss": 1.5024
      },
      {
        "step": 860,
        "loss": 1.4645
      },
      {
        "step": 870,
        "loss": 1.4986
      },
      {
        "step": 880,
        "loss": 1.4776
      },
      {
        "step": 890,
        "loss": 1.5253
      },
      {
        "step": 900,
        "loss": 1.5182
      },
      {
        "step": 910,
        "loss": 1.4985
      },
      {
        "step": 920,
        "loss": 1.5137
      },
      {
        "step": 930,
        "loss": 1.5234
      },
      {
        "step": 940,
        "loss": 1.488
      },
      {
        "step": 950,
        "loss": 1.5128
      },
      {
        "step": 960,
        "loss": 1.5182
      },
      {
        "step": 970,
        "loss": 1.4934
      },
      {
        "step": 980,
        "loss": 1.4494
      },
      {
        "step": 990,
        "loss": 1.5029
      },
      {
        "step": 1000,
        "loss": 1.4824
      },
      {
        "step": 1010,
        "loss": 1.492
      },
      {
        "step": 1020,
        "loss": 1.461
      },
      {
        "step": 1030,
        "loss": 1.5063
      },
      {
        "step": 1040,
        "loss": 1.4595
      },
      {
        "step": 1050,
        "loss": 1.4824
      },
      {
        "step": 1060,
        "loss": 1.4031
      },
      {
        "step": 1070,
        "loss": 1.4522
      },
      {
        "step": 1080,
        "loss": 1.4158
      },
      {
        "step": 1090,
        "loss": 1.4856
      },
      {
        "step": 1100,
        "loss": 1.3474
      },
      {
        "step": 1110,
        "loss": 1.3806
      },
      {
        "step": 1120,
        "loss": 1.3732
      },
      {
        "step": 1130,
        "loss": 1.4388
      },
      {
        "step": 1140,
        "loss": 1.4957
      },
      {
        "step": 1150,
        "loss": 1.3948
      },
      {
        "step": 1160,
        "loss": 1.4479
      },
      {
        "step": 1170,
        "loss": 1.4085
      },
      {
        "step": 1180,
        "loss": 1.3778
      },
      {
        "step": 1190,
        "loss": 1.4787
      },
      {
        "step": 1200,
        "loss": 1.4084
      },
      {
        "step": 1210,
        "loss": 1.4023
      },
      {
        "step": 1220,
        "loss": 1.3945
      },
      {
        "step": 1230,
        "loss": 1.3555
      },
      {
        "step": 1240,
        "loss": 1.3642
      },
      {
        "step": 1250,
        "loss": 1.3737
      },
      {
        "step": 1260,
        "loss": 1.3904
      },
      {
        "step": 1270,
        "loss": 1.4102
      },
      {
        "step": 1280,
        "loss": 1.3704
      },
      {
        "step": 1290,
        "loss": 1.4053
      },
      {
        "step": 1300,
        "loss": 1.4337
      },
      {
        "step": 1310,
        "loss": 1.3696
      },
      {
        "step": 1320,
        "loss": 1.3719
      },
      {
        "step": 1330,
        "loss": 1.3861
      },
      {
        "step": 1340,
        "loss": 1.3962
      },
      {
        "step": 1350,
        "loss": 1.3876
      },
      {
        "step": 1360,
        "loss": 1.4153
      },
      {
        "step": 1370,
        "loss": 1.4253
      },
      {
        "step": 1380,
        "loss": 1.3513
      },
      {
        "step": 1390,
        "loss": 1.3091
      },
      {
        "step": 1400,
        "loss": 1.3655
      },
      {
        "step": 1410,
        "loss": 1.3642
      },
      {
        "step": 1420,
        "loss": 1.4003
      },
      {
        "step": 1430,
        "loss": 1.4256
      },
      {
        "step": 1440,
        "loss": 1.3192
      },
      {
        "step": 1450,
        "loss": 1.3206
      },
      {
        "step": 1460,
        "loss": 1.3069
      },
      {
        "step": 1470,
        "loss": 1.365
      },
      {
        "step": 1480,
        "loss": 1.3812
      },
      {
        "step": 1490,
        "loss": 1.3812
      },
      {
        "step": 1500,
        "loss": 1.3409
      },
      {
        "step": 1510,
        "loss": 1.3273
      },
      {
        "step": 1520,
        "loss": 1.3636
      },
      {
        "step": 1530,
        "loss": 1.2385
      },
      {
        "step": 1540,
        "loss": 1.3426
      },
      {
        "step": 1550,
        "loss": 1.3714
      },
      {
        "step": 1560,
        "loss": 1.3584
      },
      {
        "step": 1570,
        "loss": 1.3209
      },
      {
        "step": 1580,
        "loss": 1.2896
      },
      {
        "step": 1590,
        "loss": 1.3613
      },
      {
        "step": 1600,
        "loss": 1.2949
      },
      {
        "step": 1610,
        "loss": 1.2956
      },
      {
        "step": 1620,
        "loss": 1.2696
      },
      {
        "step": 1630,
        "loss": 1.3396
      },
      {
        "step": 1640,
        "loss": 1.3329
      },
      {
        "step": 1650,
        "loss": 1.3536
      },
      {
        "step": 1660,
        "loss": 1.2688
      },
      {
        "step": 1670,
        "loss": 1.3026
      },
      {
        "step": 1680,
        "loss": 1.3435
      },
      {
        "step": 1690,
        "loss": 1.2517
      },
      {
        "step": 1700,
        "loss": 1.3418
      },
      {
        "step": 1710,
        "loss": 1.2988
      },
      {
        "step": 1720,
        "loss": 1.3702
      },
      {
        "step": 1730,
        "loss": 1.3851
      },
      {
        "step": 1740,
        "loss": 1.2959
      },
      {
        "step": 1750,
        "loss": 1.2745
      },
      {
        "step": 1760,
        "loss": 1.3088
      },
      {
        "step": 1770,
        "loss": 1.3413
      },
      {
        "step": 1780,
        "loss": 1.3085
      },
      {
        "step": 1790,
        "loss": 1.2417
      },
      {
        "step": 1800,
        "loss": 1.2885
      },
      {
        "step": 1810,
        "loss": 1.2803
      },
      {
        "step": 1820,
        "loss": 1.2731
      },
      {
        "step": 1830,
        "loss": 1.2759
      },
      {
        "step": 1840,
        "loss": 1.3205
      },
      {
        "step": 1850,
        "loss": 1.2639
      },
      {
        "step": 1860,
        "loss": 1.2974
      },
      {
        "step": 1870,
        "loss": 1.2737
      },
      {
        "step": 1880,
        "loss": 1.2558
      },
      {
        "step": 1890,
        "loss": 1.2546
      },
      {
        "step": 1900,
        "loss": 1.2429
      },
      {
        "step": 1910,
        "loss": 1.2603
      },
      {
        "step": 1920,
        "loss": 1.1643
      },
      {
        "step": 1930,
        "loss": 1.2938
      },
      {
        "step": 1940,
        "loss": 1.2925
      },
      {
        "step": 1950,
        "loss": 1.2312
      },
      {
        "step": 1960,
        "loss": 1.2343
      },
      {
        "step": 1970,
        "loss": 1.3137
      },
      {
        "step": 1980,
        "loss": 1.2605
      },
      {
        "step": 1990,
        "loss": 1.2254
      },
      {
        "step": 2000,
        "loss": 1.2329
      },
      {
        "step": 2010,
        "loss": 1.1891
      },
      {
        "step": 2020,
        "loss": 1.2818
      },
      {
        "step": 2030,
        "loss": 1.2565
      },
      {
        "step": 2040,
        "loss": 1.3068
      },
      {
        "step": 2050,
        "loss": 1.2528
      },
      {
        "step": 2060,
        "loss": 1.2578
      },
      {
        "step": 2070,
        "loss": 1.2987
      },
      {
        "step": 2080,
        "loss": 1.2566
      },
      {
        "step": 2090,
        "loss": 1.2641
      },
      {
        "step": 2100,
        "loss": 1.2227
      },
      {
        "step": 2110,
        "loss": 1.1852
      },
      {
        "step": 2120,
        "loss": 1.2445
      },
      {
        "step": 2130,
        "loss": 1.2085
      },
      {
        "step": 2140,
        "loss": 1.1687
      },
      {
        "step": 2150,
        "loss": 1.2216
      },
      {
        "step": 2160,
        "loss": 1.2303
      },
      {
        "step": 2170,
        "loss": 1.2381
      },
      {
        "step": 2180,
        "loss": 1.2549
      },
      {
        "step": 2190,
        "loss": 1.2047
      },
      {
        "step": 2200,
        "loss": 1.2279
      },
      {
        "step": 2210,
        "loss": 1.2667
      },
      {
        "step": 2220,
        "loss": 1.2655
      },
      {
        "step": 2230,
        "loss": 1.1581
      },
      {
        "step": 2240,
        "loss": 1.2572
      },
      {
        "step": 2250,
        "loss": 1.2172
      },
      {
        "step": 2260,
        "loss": 1.2171
      },
      {
        "step": 2270,
        "loss": 1.1867
      },
      {
        "step": 2280,
        "loss": 1.296
      },
      {
        "step": 2290,
        "loss": 1.2286
      },
      {
        "step": 2300,
        "loss": 1.2314
      },
      {
        "step": 2310,
        "loss": 1.2758
      },
      {
        "step": 2320,
        "loss": 1.1973
      },
      {
        "step": 2330,
        "loss": 1.2792
      },
      {
        "step": 2340,
        "loss": 1.1649
      },
      {
        "step": 2350,
        "loss": 1.2583
      },
      {
        "step": 2360,
        "loss": 1.1892
      },
      {
        "step": 2370,
        "loss": 1.1894
      },
      {
        "step": 2380,
        "loss": 1.1904
      },
      {
        "step": 2390,
        "loss": 1.1938
      },
      {
        "step": 2400,
        "loss": 1.241
      },
      {
        "step": 2410,
        "loss": 1.1927
      },
      {
        "step": 2420,
        "loss": 1.2581
      },
      {
        "step": 2430,
        "loss": 1.2367
      },
      {
        "step": 2440,
        "loss": 1.1952
      },
      {
        "step": 2450,
        "loss": 1.1937
      },
      {
        "step": 2460,
        "loss": 1.1555
      },
      {
        "step": 2470,
        "loss": 1.1792
      },
      {
        "step": 2480,
        "loss": 1.2042
      },
      {
        "step": 2490,
        "loss": 1.1955
      },
      {
        "step": 2500,
        "loss": 1.1324
      },
      {
        "step": 2510,
        "loss": 1.1899
      },
      {
        "step": 2520,
        "loss": 1.1789
      },
      {
        "step": 2530,
        "loss": 1.1349
      },
      {
        "step": 2540,
        "loss": 1.1236
      },
      {
        "step": 2550,
        "loss": 1.1914
      },
      {
        "step": 2560,
        "loss": 1.2017
      },
      {
        "step": 2570,
        "loss": 1.1753
      },
      {
        "step": 2580,
        "loss": 1.2226
      },
      {
        "step": 2590,
        "loss": 1.1548
      },
      {
        "step": 2600,
        "loss": 1.1793
      },
      {
        "step": 2610,
        "loss": 1.1692
      },
      {
        "step": 2620,
        "loss": 1.0996
      },
      {
        "step": 2630,
        "loss": 1.124
      },
      {
        "step": 2640,
        "loss": 1.1714
      },
      {
        "step": 2650,
        "loss": 1.1468
      },
      {
        "step": 2660,
        "loss": 1.1479
      },
      {
        "step": 2670,
        "loss": 1.1639
      },
      {
        "step": 2680,
        "loss": 1.0869
      },
      {
        "step": 2690,
        "loss": 1.1162
      },
      {
        "step": 2700,
        "loss": 1.1427
      },
      {
        "step": 2710,
        "loss": 1.1226
      },
      {
        "step": 2720,
        "loss": 1.0981
      },
      {
        "step": 2730,
        "loss": 1.1231
      },
      {
        "step": 2740,
        "loss": 1.1256
      },
      {
        "step": 2750,
        "loss": 1.0762
      },
      {
        "step": 2760,
        "loss": 1.0488
      },
      {
        "step": 2770,
        "loss": 1.0675
      },
      {
        "step": 2780,
        "loss": 1.1267
      },
      {
        "step": 2790,
        "loss": 1.1578
      },
      {
        "step": 2800,
        "loss": 1.1724
      },
      {
        "step": 2810,
        "loss": 1.1016
      },
      {
        "step": 2820,
        "loss": 1.1112
      },
      {
        "step": 2830,
        "loss": 1.1089
      },
      {
        "step": 2840,
        "loss": 1.1126
      },
      {
        "step": 2850,
        "loss": 1.0542
      },
      {
        "step": 2860,
        "loss": 1.0391
      },
      {
        "step": 2870,
        "loss": 1.0852
      },
      {
        "step": 2880,
        "loss": 1.0581
      },
      {
        "step": 2890,
        "loss": 1.1345
      },
      {
        "step": 2900,
        "loss": 1.0157
      },
      {
        "step": 2910,
        "loss": 1.0679
      },
      {
        "step": 2920,
        "loss": 1.017
      },
      {
        "step": 2930,
        "loss": 1.1281
      },
      {
        "step": 2940,
        "loss": 1.0423
      },
      {
        "step": 2950,
        "loss": 1.0638
      },
      {
        "step": 2960,
        "loss": 1.0728
      },
      {
        "step": 2970,
        "loss": 1.0802
      },
      {
        "step": 2980,
        "loss": 1.1177
      },
      {
        "step": 2990,
        "loss": 1.1024
      },
      {
        "step": 3000,
        "loss": 1.0771
      },
      {
        "step": 3010,
        "loss": 0.9882
      },
      {
        "step": 3020,
        "loss": 1.0224
      },
      {
        "step": 3030,
        "loss": 1.0662
      },
      {
        "step": 3040,
        "loss": 1.0231
      },
      {
        "step": 3050,
        "loss": 1.0448
      },
      {
        "step": 3060,
        "loss": 1.0657
      },
      {
        "step": 3070,
        "loss": 1.0114
      },
      {
        "step": 3080,
        "loss": 1.0283
      },
      {
        "step": 3090,
        "loss": 1.0684
      },
      {
        "step": 3100,
        "loss": 1.0656
      },
      {
        "step": 3110,
        "loss": 1.0396
      },
      {
        "step": 3120,
        "loss": 1.0319
      },
      {
        "step": 3130,
        "loss": 1.0698
      },
      {
        "step": 3140,
        "loss": 1.0666
      },
      {
        "step": 3150,
        "loss": 1.073
      },
      {
        "step": 3160,
        "loss": 1.0436
      },
      {
        "step": 3170,
        "loss": 0.9864
      },
      {
        "step": 3180,
        "loss": 1.02
      },
      {
        "step": 3190,
        "loss": 1.0167
      },
      {
        "step": 3200,
        "loss": 1.0604
      },
      {
        "step": 3210,
        "loss": 1.0505
      },
      {
        "step": 3220,
        "loss": 1.0444
      },
      {
        "step": 3230,
        "loss": 1.051
      },
      {
        "step": 3240,
        "loss": 1.1036
      },
      {
        "step": 3250,
        "loss": 1.0166
      },
      {
        "step": 3260,
        "loss": 1.0771
      },
      {
        "step": 3270,
        "loss": 0.9951
      },
      {
        "step": 3280,
        "loss": 1.0333
      },
      {
        "step": 3290,
        "loss": 1.0165
      },
      {
        "step": 3300,
        "loss": 1.0552
      },
      {
        "step": 3310,
        "loss": 1.0245
      },
      {
        "step": 3320,
        "loss": 0.9781
      },
      {
        "step": 3330,
        "loss": 1.0386
      },
      {
        "step": 3340,
        "loss": 1.0787
      },
      {
        "step": 3350,
        "loss": 1.0228
      },
      {
        "step": 3360,
        "loss": 1.0403
      },
      {
        "step": 3370,
        "loss": 1.0615
      },
      {
        "step": 3380,
        "loss": 0.9488
      },
      {
        "step": 3390,
        "loss": 0.9849
      },
      {
        "step": 3400,
        "loss": 1.026
      },
      {
        "step": 3410,
        "loss": 1.0735
      },
      {
        "step": 3420,
        "loss": 0.9784
      },
      {
        "step": 3430,
        "loss": 0.964
      },
      {
        "step": 3440,
        "loss": 0.948
      },
      {
        "step": 3450,
        "loss": 0.9409
      },
      {
        "step": 3460,
        "loss": 0.9689
      },
      {
        "step": 3470,
        "loss": 0.9352
      },
      {
        "step": 3480,
        "loss": 0.9874
      },
      {
        "step": 3490,
        "loss": 0.9411
      },
      {
        "step": 3500,
        "loss": 0.9534
      },
      {
        "step": 3510,
        "loss": 0.9366
      },
      {
        "step": 3520,
        "loss": 0.9966
      },
      {
        "step": 3530,
        "loss": 1.0249
      },
      {
        "step": 3540,
        "loss": 0.8956
      },
      {
        "step": 3550,
        "loss": 0.9146
      },
      {
        "step": 3560,
        "loss": 0.9353
      },
      {
        "step": 3570,
        "loss": 0.898
      },
      {
        "step": 3580,
        "loss": 0.9134
      },
      {
        "step": 3590,
        "loss": 0.9685
      },
      {
        "step": 3600,
        "loss": 0.9834
      },
      {
        "step": 3610,
        "loss": 0.967
      },
      {
        "step": 3620,
        "loss": 0.9549
      },
      {
        "step": 3630,
        "loss": 0.8967
      },
      {
        "step": 3640,
        "loss": 0.8988
      },
      {
        "step": 3650,
        "loss": 0.9254
      },
      {
        "step": 3660,
        "loss": 0.9356
      },
      {
        "step": 3670,
        "loss": 0.9493
      },
      {
        "step": 3680,
        "loss": 0.9143
      },
      {
        "step": 3690,
        "loss": 0.8948
      },
      {
        "step": 3700,
        "loss": 0.8921
      },
      {
        "step": 3710,
        "loss": 0.9306
      },
      {
        "step": 3720,
        "loss": 0.9634
      },
      {
        "step": 3730,
        "loss": 0.9
      },
      {
        "step": 3740,
        "loss": 0.9281
      },
      {
        "step": 3750,
        "loss": 0.9476
      },
      {
        "step": 3760,
        "loss": 0.8031
      },
      {
        "step": 3770,
        "loss": 0.912
      },
      {
        "step": 3780,
        "loss": 0.8619
      },
      {
        "step": 3790,
        "loss": 0.886
      },
      {
        "step": 3800,
        "loss": 0.8955
      },
      {
        "step": 3810,
        "loss": 0.9268
      },
      {
        "step": 3820,
        "loss": 0.833
      },
      {
        "step": 3830,
        "loss": 0.9936
      },
      {
        "step": 3840,
        "loss": 0.8962
      },
      {
        "step": 3850,
        "loss": 0.8254
      },
      {
        "step": 3860,
        "loss": 0.8679
      },
      {
        "step": 3870,
        "loss": 0.8877
      },
      {
        "step": 3880,
        "loss": 0.8462
      },
      {
        "step": 3890,
        "loss": 0.8059
      },
      {
        "step": 3900,
        "loss": 0.8867
      },
      {
        "step": 3910,
        "loss": 0.8854
      },
      {
        "step": 3920,
        "loss": 0.861
      },
      {
        "step": 3930,
        "loss": 0.8773
      },
      {
        "step": 3940,
        "loss": 0.8449
      },
      {
        "step": 3950,
        "loss": 0.842
      },
      {
        "step": 3960,
        "loss": 0.8655
      },
      {
        "step": 3970,
        "loss": 0.9214
      },
      {
        "step": 3980,
        "loss": 0.7997
      },
      {
        "step": 3990,
        "loss": 0.8595
      },
      {
        "step": 4000,
        "loss": 0.9164
      },
      {
        "step": 4010,
        "loss": 0.8444
      },
      {
        "step": 4020,
        "loss": 0.8135
      },
      {
        "step": 4030,
        "loss": 0.8291
      },
      {
        "step": 4040,
        "loss": 0.7624
      },
      {
        "step": 4050,
        "loss": 0.8256
      },
      {
        "step": 4060,
        "loss": 0.8578
      },
      {
        "step": 4070,
        "loss": 0.835
      },
      {
        "step": 4080,
        "loss": 0.812
      },
      {
        "step": 4090,
        "loss": 0.8605
      },
      {
        "step": 4100,
        "loss": 0.7754
      },
      {
        "step": 4110,
        "loss": 0.8302
      },
      {
        "step": 4120,
        "loss": 0.7674
      },
      {
        "step": 4130,
        "loss": 0.8174
      },
      {
        "step": 4140,
        "loss": 0.8442
      },
      {
        "step": 4150,
        "loss": 0.766
      },
      {
        "step": 4160,
        "loss": 0.7629
      },
      {
        "step": 4170,
        "loss": 0.784
      },
      {
        "step": 4180,
        "loss": 0.8122
      },
      {
        "step": 4190,
        "loss": 0.8132
      },
      {
        "step": 4200,
        "loss": 0.8362
      },
      {
        "step": 4210,
        "loss": 0.7927
      },
      {
        "step": 4220,
        "loss": 0.7461
      },
      {
        "step": 4230,
        "loss": 0.77
      },
      {
        "step": 4240,
        "loss": 0.8431
      },
      {
        "step": 4250,
        "loss": 0.7966
      },
      {
        "step": 4260,
        "loss": 0.7378
      },
      {
        "step": 4270,
        "loss": 0.778
      },
      {
        "step": 4280,
        "loss": 0.8107
      },
      {
        "step": 4290,
        "loss": 0.8667
      },
      {
        "step": 4300,
        "loss": 0.8391
      },
      {
        "step": 4310,
        "loss": 0.7502
      },
      {
        "step": 4320,
        "loss": 0.7432
      },
      {
        "step": 4330,
        "loss": 0.8035
      },
      {
        "step": 4340,
        "loss": 0.7329
      },
      {
        "step": 4350,
        "loss": 0.8069
      },
      {
        "step": 4360,
        "loss": 0.696
      },
      {
        "step": 4370,
        "loss": 0.7194
      },
      {
        "step": 4380,
        "loss": 0.8316
      },
      {
        "step": 4390,
        "loss": 0.737
      },
      {
        "step": 4400,
        "loss": 0.7258
      },
      {
        "step": 4410,
        "loss": 0.6409
      },
      {
        "step": 4420,
        "loss": 0.7722
      },
      {
        "step": 4430,
        "loss": 0.7254
      },
      {
        "step": 4440,
        "loss": 0.7798
      },
      {
        "step": 4450,
        "loss": 0.7615
      },
      {
        "step": 4460,
        "loss": 0.8476
      },
      {
        "step": 4470,
        "loss": 0.7764
      },
      {
        "step": 4480,
        "loss": 0.7559
      },
      {
        "step": 4490,
        "loss": 0.7726
      },
      {
        "step": 4500,
        "loss": 0.7657
      },
      {
        "step": 4510,
        "loss": 0.7162
      },
      {
        "step": 4520,
        "loss": 0.7478
      },
      {
        "step": 4530,
        "loss": 0.8175
      },
      {
        "step": 4540,
        "loss": 0.7452
      },
      {
        "step": 4550,
        "loss": 0.7936
      },
      {
        "step": 4560,
        "loss": 0.7184
      },
      {
        "step": 4570,
        "loss": 0.6903
      },
      {
        "step": 4580,
        "loss": 0.769
      },
      {
        "step": 4590,
        "loss": 0.7032
      },
      {
        "step": 4600,
        "loss": 0.7039
      },
      {
        "step": 4610,
        "loss": 0.7164
      },
      {
        "step": 4620,
        "loss": 0.7031
      },
      {
        "step": 4630,
        "loss": 0.7259
      },
      {
        "step": 4640,
        "loss": 0.7129
      },
      {
        "step": 4650,
        "loss": 0.7297
      },
      {
        "step": 4660,
        "loss": 0.6931
      },
      {
        "step": 4670,
        "loss": 0.743
      },
      {
        "step": 4680,
        "loss": 0.6459
      },
      {
        "step": 4690,
        "loss": 0.6621
      },
      {
        "step": 4700,
        "loss": 0.7131
      },
      {
        "step": 4710,
        "loss": 0.6568
      },
      {
        "step": 4720,
        "loss": 0.6832
      },
      {
        "step": 4730,
        "loss": 0.7392
      },
      {
        "step": 4740,
        "loss": 0.6449
      },
      {
        "step": 4750,
        "loss": 0.7326
      },
      {
        "step": 4760,
        "loss": 0.8108
      },
      {
        "step": 4770,
        "loss": 0.7215
      },
      {
        "step": 4780,
        "loss": 0.7095
      },
      {
        "step": 4790,
        "loss": 0.7296
      },
      {
        "step": 4800,
        "loss": 0.7101
      },
      {
        "step": 4810,
        "loss": 0.6285
      },
      {
        "step": 4820,
        "loss": 0.6943
      },
      {
        "step": 4830,
        "loss": 0.7256
      },
      {
        "step": 4840,
        "loss": 0.6641
      },
      {
        "step": 4850,
        "loss": 0.6544
      },
      {
        "step": 4860,
        "loss": 0.6683
      },
      {
        "step": 4870,
        "loss": 0.6985
      },
      {
        "step": 4880,
        "loss": 0.626
      },
      {
        "step": 4890,
        "loss": 0.6339
      },
      {
        "step": 4900,
        "loss": 0.641
      },
      {
        "step": 4910,
        "loss": 0.6144
      },
      {
        "step": 4920,
        "loss": 0.7348
      },
      {
        "step": 4930,
        "loss": 0.5943
      },
      {
        "step": 4940,
        "loss": 0.6436
      },
      {
        "step": 4950,
        "loss": 0.6262
      },
      {
        "step": 4960,
        "loss": 0.6007
      },
      {
        "step": 4970,
        "loss": 0.6274
      },
      {
        "step": 4980,
        "loss": 0.6163
      },
      {
        "step": 4990,
        "loss": 0.6909
      },
      {
        "step": 5000,
        "loss": 0.6004
      }
    ],
    "evals": [
      {
        "step": 100,
        "loss": 2.526
      },
      {
        "step": 200,
        "loss": 2.406
      },
      {
        "step": 300,
        "loss": 2.1358
      },
      {
        "step": 400,
        "loss": 1.9975
      },
      {
        "step": 500,
        "loss": 1.8884
      },
      {
        "step": 600,
        "loss": 1.8203
      },
      {
        "step": 700,
        "loss": 1.7593
      },
      {
        "step": 800,
        "loss": 1.7303
      },
      {
        "step": 900,
        "loss": 1.7066
      },
      {
        "step": 1000,
        "loss": 1.6656
      },
      {
        "step": 1100,
        "loss": 1.6383
      },
      {
        "step": 1200,
        "loss": 1.6236
      },
      {
        "step": 1300,
        "loss": 1.5885
      },
      {
        "step": 1400,
        "loss": 1.5798
      },
      {
        "step": 1500,
        "loss": 1.5704
      },
      {
        "step": 1600,
        "loss": 1.5628
      },
      {
        "step": 1700,
        "loss": 1.5696
      },
      {
        "step": 1800,
        "loss": 1.5381
      },
      {
        "step": 1900,
        "loss": 1.5385
      },
      {
        "step": 2000,
        "loss": 1.5334
      },
      {
        "step": 2100,
        "loss": 1.5224
      },
      {
        "step": 2200,
        "loss": 1.5269
      },
      {
        "step": 2300,
        "loss": 1.5239
      },
      {
        "step": 2400,
        "loss": 1.5073
      },
      {
        "step": 2500,
        "loss": 1.5111
      },
      {
        "step": 2600,
        "loss": 1.5184
      },
      {
        "step": 2700,
        "loss": 1.5263
      },
      {
        "step": 2800,
        "loss": 1.5321
      },
      {
        "step": 2900,
        "loss": 1.5386
      },
      {
        "step": 3000,
        "loss": 1.5403
      },
      {
        "step": 3100,
        "loss": 1.5465
      },
      {
        "step": 3200,
        "loss": 1.5673
      },
      {
        "step": 3300,
        "loss": 1.5569
      },
      {
        "step": 3400,
        "loss": 1.5883
      },
      {
        "step": 3500,
        "loss": 1.6094
      },
      {
        "step": 3600,
        "loss": 1.6092
      },
      {
        "step": 3700,
        "loss": 1.634
      },
      {
        "step": 3800,
        "loss": 1.649
      },
      {
        "step": 3900,
        "loss": 1.6636
      },
      {
        "step": 4000,
        "loss": 1.6863
      },
      {
        "step": 4100,
        "loss": 1.7201
      },
      {
        "step": 4200,
        "loss": 1.7379
      },
      {
        "step": 4300,
        "loss": 1.7642
      },
      {
        "step": 4400,
        "loss": 1.7906
      },
      {
        "step": 4500,
        "loss": 1.8122
      },
      {
        "step": 4600,
        "loss": 1.8613
      },
      {
        "step": 4700,
        "loss": 1.8807
      },
      {
        "step": 4800,
        "loss": 1.8816
      },
      {
        "step": 4900,
        "loss": 1.9241
      },
      {
        "step": 5000,
        "loss": 1.9675
      }
    ],
    "sample": "MOPSA:\nWhy,\nHave we boides unterbned by the heaven he not\nAnd may be one, his practise to his act of thy lady?\n\nPAULINA:\n'Tis not to renowned by yours, is seen cut soul.\nUnhappier now to the sea out of heaven,\nMakes thy secret with my some sword, and my father.\n\nLEONTES:\nIt would be villain, make it by the male,\nWhipteen shall obey the most deed world entreat.\n\nPERDITA:\nOnce me not;\nUnless you think's I dream no more; not my hand,\nDo being peace now, and sitting and faming\nTo more into the face.\n\nPAULINA:\nNo, no more than she will she to be man\nWhen I best but seen you all seeing laws\nBehind in presence, and you can for this\nThat I make up my place.\n\nLEONTES:\nHeavenspurge his highness!\n\nLEON"
  },
  "flash": {
    "shape": {
      "B": 16,
      "T": 256,
      "C": 384,
      "NH": 6
    },
    "fwd": {
      "unfused": {
        "name": "unfused (3 kernels)",
        "ms": 1.13,
        "medMs": 1.138,
        "gflops": 715.1,
        "speedup": 1.0,
        "errs": []
      },
      "best": {
        "name": "br64 bc32 t128 4x4",
        "ms": 0.333,
        "medMs": 0.346,
        "gflops": 2429.2,
        "speedup": 3.4,
        "errs": [
          2.09e-07
        ]
      },
      "configs": [
        {
          "name": "br64 bc64 t128 4x8",
          "ms": 0.446,
          "medMs": 0.449,
          "gflops": 1810.8,
          "speedup": 2.53,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br64 bc32 t128 4x4",
          "ms": 0.333,
          "medMs": 0.346,
          "gflops": 2429.2,
          "speedup": 3.4,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br64 bc64 t256 4x4",
          "ms": 0.355,
          "medMs": 0.357,
          "gflops": 2275.2,
          "speedup": 3.18,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br128 bc32 t256 4x4",
          "ms": 0.424,
          "medMs": 0.426,
          "gflops": 1907.0,
          "speedup": 2.67,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br32 bc32 t64 4x4",
          "ms": 0.391,
          "medMs": 0.397,
          "gflops": 2066.8,
          "speedup": 2.89,
          "errs": [
            2.09e-07
          ]
        }
      ]
    },
    "bwd": {
      "unfused": {
        "name": "unfused (7 kernels)",
        "ms": 1.905,
        "medMs": 1.919,
        "gflops": 1485.6,
        "speedup": 1.0,
        "errs": []
      },
      "best": {
        "name": "br32 bc32 t128 kv4x4 q4x4",
        "ms": 1.597,
        "medMs": 1.623,
        "gflops": 1771.3,
        "speedup": 1.19,
        "errs": [
          3e-07,
          4.19e-07,
          3.26e-07
        ]
      },
      "configs": [
        {
          "name": "br64 bc32 t128 kv4x4 q8x4",
          "ms": 1.783,
          "medMs": 1.793,
          "gflops": 1587.2,
          "speedup": 1.07,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br64 bc32 t128 kv4x4 q4x8",
          "ms": 1.96,
          "medMs": 1.969,
          "gflops": 1443.7,
          "speedup": 0.97,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc32 t64  kv4x8 q4x8",
          "ms": 2.091,
          "medMs": 2.113,
          "gflops": 1353.2,
          "speedup": 0.91,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc32 t64  kv8x4 q8x4",
          "ms": 1.64,
          "medMs": 1.658,
          "gflops": 1724.9,
          "speedup": 1.16,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc32 t128 kv4x4 q4x4",
          "ms": 1.597,
          "medMs": 1.623,
          "gflops": 1771.3,
          "speedup": 1.19,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc64 t128 kv8x4 q4x4",
          "ms": 2.0,
          "medMs": 2.009,
          "gflops": 1414.9,
          "speedup": 0.95,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        }
      ]
    },
    "err": {
      "out": 2.09e-07,
      "dq": 3e-07,
      "dk": 4.19e-07,
      "dv": 3.26e-07
    },
    "savedMbPerLayer": 50.3,
    "memory": [
      {
        "ctx": 256,
        "fused": 0.91,
        "unfused": 1.23
      },
      {
        "ctx": 512,
        "fused": 1.65,
        "unfused": 2.64
      },
      {
        "ctx": 1024,
        "fused": 3.15,
        "unfused": 6.42
      },
      {
        "ctx": 2048,
        "fused": 6.13,
        "unfused": 17.94
      },
      {
        "ctx": 3072,
        "fused": 9.12,
        "unfused": null
      },
      {
        "ctx": 4096,
        "fused": 12.11,
        "unfused": null
      }
    ],
    "profile": [
      {
        "name": "forward",
        "l1": 71.35,
        "dram": 40.32,
        "compute": 38.43,
        "occupancy": 16.11
      },
      {
        "name": "backward dK/dV",
        "l1": 87.67,
        "dram": 23.85,
        "compute": 35.78,
        "occupancy": 16.37
      },
      {
        "name": "backward dQ",
        "l1": 88.22,
        "dram": 21.03,
        "compute": 34.25,
        "occupancy": 16.33
      }
    ]
  }
} as const;
