// GENERATED by tools/make_site_data.py -- do not edit.
// Numbers come from bench/results.csv and bench/logs/train_final.log.

export const data = {
  "kernels": [
    {
      "id": 1,
      "name": "naive",
      "gflops": 82.79,
      "pct": 1.17,
      "note": "one thread per output element, uncoalesced",
      "intensity": 0.25,
      "bySize": {
        "512": 1.81,
        "1024": 1.37,
        "2048": 1.21,
        "4096": 1.17
      }
    },
    {
      "id": 2,
      "name": "coalesced",
      "gflops": 648.01,
      "pct": 9.16,
      "note": "swapped which index maps to threadIdx.x",
      "intensity": 0.25,
      "bySize": {
        "512": 14.71,
        "1024": 11.26,
        "2048": 10.0,
        "4096": 9.16
      }
    },
    {
      "id": 3,
      "name": "smem",
      "gflops": 814.67,
      "pct": 11.52,
      "note": "32x32 shared-memory tile",
      "intensity": 8,
      "bySize": {
        "512": 18.57,
        "1024": 14.29,
        "2048": 12.65,
        "4096": 11.52
      }
    },
    {
      "id": 4,
      "name": "tile1d",
      "gflops": 2600.26,
      "pct": 36.79,
      "note": "8 outputs per thread (TM=8)",
      "intensity": 16,
      "bySize": {
        "512": 50.39,
        "1024": 39.33,
        "2048": 38.03,
        "4096": 36.79
      }
    },
    {
      "id": 5,
      "name": "tile2d",
      "gflops": 5255.4,
      "pct": 74.35,
      "note": "8x8 register tile, outer-product form",
      "intensity": 32,
      "bySize": {
        "512": 43.05,
        "1024": 70.52,
        "2048": 68.31,
        "4096": 74.35
      }
    },
    {
      "id": 6,
      "name": "vectorized",
      "gflops": 6244.14,
      "pct": 88.32,
      "note": "float4 loads + transposed A tile",
      "intensity": 32,
      "bySize": {
        "512": 55.56,
        "1024": 92.17,
        "2048": 83.46,
        "4096": 88.32
      }
    },
    {
      "id": 7,
      "name": "warptile",
      "gflops": 6398.94,
      "pct": 90.51,
      "note": "block -> warp -> thread blocking",
      "intensity": 32,
      "bySize": {
        "512": 54.17,
        "1024": 96.99,
        "2048": 84.85,
        "4096": 90.51
      }
    },
    {
      "id": 8,
      "name": "dbuffer",
      "gflops": 6711.56,
      "pct": 94.96,
      "note": "double-buffered SMEM, one barrier per chunk",
      "intensity": 32,
      "bySize": {
        "512": 54.62,
        "1024": 99.46,
        "2048": 89.03,
        "4096": 94.96
      }
    },
    {
      "id": 9,
      "name": "tensorcore",
      "gflops": 8298.88,
      "pct": 117.39,
      "note": "WMMA m16n16k8 TF32 tensor cores",
      "intensity": 64,
      "bySize": {
        "512": 65.0,
        "1024": 112.03,
        "2048": 108.89,
        "4096": 117.39
      }
    }
  ],
  "tf32": {
    "dbuffer": {
      "1024": {
        "gflops": 5890.88,
        "pct": 66.57,
        "cublasTf32": 8848.74
      },
      "2048": {
        "gflops": 6045.84,
        "pct": 64.9,
        "cublasTf32": 9310.33
      },
      "4096": {
        "gflops": 6715.92,
        "pct": 63.71,
        "cublasTf32": 10521.1
      }
    },
    "tensorcore": {
      "1024": {
        "gflops": 6615.62,
        "pct": 74.76,
        "cublasTf32": 8848.74
      },
      "2048": {
        "gflops": 7413.71,
        "pct": 79.58,
        "cublasTf32": 9305.17
      },
      "4096": {
        "gflops": 8287.09,
        "pct": 78.85,
        "cublasTf32": 10505.46
      }
    }
  },
  "cublas": 7069.3,
  "benchSize": 4096,
  "sizes": [
    512,
    1024,
    2048,
    4096
  ],
  "training": {
    "totalSteps": 5000,
    "bestVal": 1.5035,
    "bestStep": 2400,
    "finalTrain": 0.6463,
    "finalVal": 1.9647,
    "msPerStep": 86.2,
    "tokPerSec": 47531,
    "gflops": 3415,
    "curve": [
      {
        "step": 1,
        "loss": 4.2617
      },
      {
        "step": 10,
        "loss": 3.1103
      },
      {
        "step": 20,
        "loss": 2.743
      },
      {
        "step": 30,
        "loss": 2.6149
      },
      {
        "step": 40,
        "loss": 2.5989
      },
      {
        "step": 50,
        "loss": 2.5335
      },
      {
        "step": 60,
        "loss": 2.5306
      },
      {
        "step": 70,
        "loss": 2.4765
      },
      {
        "step": 80,
        "loss": 2.4957
      },
      {
        "step": 90,
        "loss": 2.5084
      },
      {
        "step": 100,
        "loss": 2.4958
      },
      {
        "step": 110,
        "loss": 2.5246
      },
      {
        "step": 120,
        "loss": 2.4466
      },
      {
        "step": 130,
        "loss": 2.427
      },
      {
        "step": 140,
        "loss": 2.4544
      },
      {
        "step": 150,
        "loss": 2.4169
      },
      {
        "step": 160,
        "loss": 2.4101
      },
      {
        "step": 170,
        "loss": 2.4118
      },
      {
        "step": 180,
        "loss": 2.3986
      },
      {
        "step": 190,
        "loss": 2.3878
      },
      {
        "step": 200,
        "loss": 2.3841
      },
      {
        "step": 210,
        "loss": 2.3922
      },
      {
        "step": 220,
        "loss": 2.3115
      },
      {
        "step": 230,
        "loss": 2.2552
      },
      {
        "step": 240,
        "loss": 2.2053
      },
      {
        "step": 250,
        "loss": 2.159
      },
      {
        "step": 260,
        "loss": 2.12
      },
      {
        "step": 270,
        "loss": 2.1412
      },
      {
        "step": 280,
        "loss": 2.0726
      },
      {
        "step": 290,
        "loss": 2.0874
      },
      {
        "step": 300,
        "loss": 2.0167
      },
      {
        "step": 310,
        "loss": 2.0239
      },
      {
        "step": 320,
        "loss": 2.0349
      },
      {
        "step": 330,
        "loss": 2.0027
      },
      {
        "step": 340,
        "loss": 1.9973
      },
      {
        "step": 350,
        "loss": 1.907
      },
      {
        "step": 360,
        "loss": 1.8697
      },
      {
        "step": 370,
        "loss": 1.9349
      },
      {
        "step": 380,
        "loss": 1.8643
      },
      {
        "step": 390,
        "loss": 1.8086
      },
      {
        "step": 400,
        "loss": 1.9011
      },
      {
        "step": 410,
        "loss": 1.8044
      },
      {
        "step": 420,
        "loss": 1.8346
      },
      {
        "step": 430,
        "loss": 1.8886
      },
      {
        "step": 440,
        "loss": 1.833
      },
      {
        "step": 450,
        "loss": 1.8407
      },
      {
        "step": 460,
        "loss": 1.8058
      },
      {
        "step": 470,
        "loss": 1.7628
      },
      {
        "step": 480,
        "loss": 1.8069
      },
      {
        "step": 490,
        "loss": 1.6812
      },
      {
        "step": 500,
        "loss": 1.7413
      },
      {
        "step": 510,
        "loss": 1.7106
      },
      {
        "step": 520,
        "loss": 1.6535
      },
      {
        "step": 530,
        "loss": 1.6933
      },
      {
        "step": 540,
        "loss": 1.775
      },
      {
        "step": 550,
        "loss": 1.6879
      },
      {
        "step": 560,
        "loss": 1.7759
      },
      {
        "step": 570,
        "loss": 1.6631
      },
      {
        "step": 580,
        "loss": 1.6399
      },
      {
        "step": 590,
        "loss": 1.7307
      },
      {
        "step": 600,
        "loss": 1.6476
      },
      {
        "step": 610,
        "loss": 1.6766
      },
      {
        "step": 620,
        "loss": 1.6156
      },
      {
        "step": 630,
        "loss": 1.5683
      },
      {
        "step": 640,
        "loss": 1.6847
      },
      {
        "step": 650,
        "loss": 1.6023
      },
      {
        "step": 660,
        "loss": 1.579
      },
      {
        "step": 670,
        "loss": 1.647
      },
      {
        "step": 680,
        "loss": 1.6508
      },
      {
        "step": 690,
        "loss": 1.5547
      },
      {
        "step": 700,
        "loss": 1.5828
      },
      {
        "step": 710,
        "loss": 1.5578
      },
      {
        "step": 720,
        "loss": 1.6125
      },
      {
        "step": 730,
        "loss": 1.6275
      },
      {
        "step": 740,
        "loss": 1.5965
      },
      {
        "step": 750,
        "loss": 1.6033
      },
      {
        "step": 760,
        "loss": 1.5676
      },
      {
        "step": 770,
        "loss": 1.528
      },
      {
        "step": 780,
        "loss": 1.6251
      },
      {
        "step": 790,
        "loss": 1.5303
      },
      {
        "step": 800,
        "loss": 1.5097
      },
      {
        "step": 810,
        "loss": 1.5912
      },
      {
        "step": 820,
        "loss": 1.5219
      },
      {
        "step": 830,
        "loss": 1.564
      },
      {
        "step": 840,
        "loss": 1.5639
      },
      {
        "step": 850,
        "loss": 1.503
      },
      {
        "step": 860,
        "loss": 1.4649
      },
      {
        "step": 870,
        "loss": 1.4997
      },
      {
        "step": 880,
        "loss": 1.4708
      },
      {
        "step": 890,
        "loss": 1.5322
      },
      {
        "step": 900,
        "loss": 1.5083
      },
      {
        "step": 910,
        "loss": 1.5112
      },
      {
        "step": 920,
        "loss": 1.5302
      },
      {
        "step": 930,
        "loss": 1.5207
      },
      {
        "step": 940,
        "loss": 1.5017
      },
      {
        "step": 950,
        "loss": 1.517
      },
      {
        "step": 960,
        "loss": 1.5097
      },
      {
        "step": 970,
        "loss": 1.4927
      },
      {
        "step": 980,
        "loss": 1.4494
      },
      {
        "step": 990,
        "loss": 1.5111
      },
      {
        "step": 1000,
        "loss": 1.4791
      },
      {
        "step": 1010,
        "loss": 1.4885
      },
      {
        "step": 1020,
        "loss": 1.4786
      },
      {
        "step": 1030,
        "loss": 1.5118
      },
      {
        "step": 1040,
        "loss": 1.4772
      },
      {
        "step": 1050,
        "loss": 1.4894
      },
      {
        "step": 1060,
        "loss": 1.405
      },
      {
        "step": 1070,
        "loss": 1.4606
      },
      {
        "step": 1080,
        "loss": 1.4215
      },
      {
        "step": 1090,
        "loss": 1.4941
      },
      {
        "step": 1100,
        "loss": 1.3518
      },
      {
        "step": 1110,
        "loss": 1.3854
      },
      {
        "step": 1120,
        "loss": 1.377
      },
      {
        "step": 1130,
        "loss": 1.4366
      },
      {
        "step": 1140,
        "loss": 1.5008
      },
      {
        "step": 1150,
        "loss": 1.39
      },
      {
        "step": 1160,
        "loss": 1.4497
      },
      {
        "step": 1170,
        "loss": 1.4085
      },
      {
        "step": 1180,
        "loss": 1.3886
      },
      {
        "step": 1190,
        "loss": 1.4751
      },
      {
        "step": 1200,
        "loss": 1.4079
      },
      {
        "step": 1210,
        "loss": 1.3886
      },
      {
        "step": 1220,
        "loss": 1.3874
      },
      {
        "step": 1230,
        "loss": 1.3611
      },
      {
        "step": 1240,
        "loss": 1.3725
      },
      {
        "step": 1250,
        "loss": 1.3682
      },
      {
        "step": 1260,
        "loss": 1.3856
      },
      {
        "step": 1270,
        "loss": 1.41
      },
      {
        "step": 1280,
        "loss": 1.3648
      },
      {
        "step": 1290,
        "loss": 1.4093
      },
      {
        "step": 1300,
        "loss": 1.4433
      },
      {
        "step": 1310,
        "loss": 1.3825
      },
      {
        "step": 1320,
        "loss": 1.3788
      },
      {
        "step": 1330,
        "loss": 1.3903
      },
      {
        "step": 1340,
        "loss": 1.4033
      },
      {
        "step": 1350,
        "loss": 1.3839
      },
      {
        "step": 1360,
        "loss": 1.4225
      },
      {
        "step": 1370,
        "loss": 1.425
      },
      {
        "step": 1380,
        "loss": 1.357
      },
      {
        "step": 1390,
        "loss": 1.3325
      },
      {
        "step": 1400,
        "loss": 1.3736
      },
      {
        "step": 1410,
        "loss": 1.3733
      },
      {
        "step": 1420,
        "loss": 1.3991
      },
      {
        "step": 1430,
        "loss": 1.4234
      },
      {
        "step": 1440,
        "loss": 1.3268
      },
      {
        "step": 1450,
        "loss": 1.3284
      },
      {
        "step": 1460,
        "loss": 1.3074
      },
      {
        "step": 1470,
        "loss": 1.3623
      },
      {
        "step": 1480,
        "loss": 1.3814
      },
      {
        "step": 1490,
        "loss": 1.3863
      },
      {
        "step": 1500,
        "loss": 1.3557
      },
      {
        "step": 1510,
        "loss": 1.3414
      },
      {
        "step": 1520,
        "loss": 1.3625
      },
      {
        "step": 1530,
        "loss": 1.2414
      },
      {
        "step": 1540,
        "loss": 1.3682
      },
      {
        "step": 1550,
        "loss": 1.3713
      },
      {
        "step": 1560,
        "loss": 1.3712
      },
      {
        "step": 1570,
        "loss": 1.32
      },
      {
        "step": 1580,
        "loss": 1.285
      },
      {
        "step": 1590,
        "loss": 1.3576
      },
      {
        "step": 1600,
        "loss": 1.2997
      },
      {
        "step": 1610,
        "loss": 1.2973
      },
      {
        "step": 1620,
        "loss": 1.2773
      },
      {
        "step": 1630,
        "loss": 1.3465
      },
      {
        "step": 1640,
        "loss": 1.332
      },
      {
        "step": 1650,
        "loss": 1.3572
      },
      {
        "step": 1660,
        "loss": 1.2793
      },
      {
        "step": 1670,
        "loss": 1.3039
      },
      {
        "step": 1680,
        "loss": 1.3495
      },
      {
        "step": 1690,
        "loss": 1.2585
      },
      {
        "step": 1700,
        "loss": 1.3528
      },
      {
        "step": 1710,
        "loss": 1.304
      },
      {
        "step": 1720,
        "loss": 1.3709
      },
      {
        "step": 1730,
        "loss": 1.3806
      },
      {
        "step": 1740,
        "loss": 1.3005
      },
      {
        "step": 1750,
        "loss": 1.2688
      },
      {
        "step": 1760,
        "loss": 1.3169
      },
      {
        "step": 1770,
        "loss": 1.3399
      },
      {
        "step": 1780,
        "loss": 1.3052
      },
      {
        "step": 1790,
        "loss": 1.2406
      },
      {
        "step": 1800,
        "loss": 1.2846
      },
      {
        "step": 1810,
        "loss": 1.2832
      },
      {
        "step": 1820,
        "loss": 1.275
      },
      {
        "step": 1830,
        "loss": 1.2731
      },
      {
        "step": 1840,
        "loss": 1.3252
      },
      {
        "step": 1850,
        "loss": 1.2557
      },
      {
        "step": 1860,
        "loss": 1.3096
      },
      {
        "step": 1870,
        "loss": 1.2869
      },
      {
        "step": 1880,
        "loss": 1.266
      },
      {
        "step": 1890,
        "loss": 1.2686
      },
      {
        "step": 1900,
        "loss": 1.2457
      },
      {
        "step": 1910,
        "loss": 1.2743
      },
      {
        "step": 1920,
        "loss": 1.1876
      },
      {
        "step": 1930,
        "loss": 1.3015
      },
      {
        "step": 1940,
        "loss": 1.2909
      },
      {
        "step": 1950,
        "loss": 1.2409
      },
      {
        "step": 1960,
        "loss": 1.2402
      },
      {
        "step": 1970,
        "loss": 1.3106
      },
      {
        "step": 1980,
        "loss": 1.2687
      },
      {
        "step": 1990,
        "loss": 1.2386
      },
      {
        "step": 2000,
        "loss": 1.253
      },
      {
        "step": 2010,
        "loss": 1.194
      },
      {
        "step": 2020,
        "loss": 1.2886
      },
      {
        "step": 2030,
        "loss": 1.2587
      },
      {
        "step": 2040,
        "loss": 1.3209
      },
      {
        "step": 2050,
        "loss": 1.2693
      },
      {
        "step": 2060,
        "loss": 1.2599
      },
      {
        "step": 2070,
        "loss": 1.2963
      },
      {
        "step": 2080,
        "loss": 1.2535
      },
      {
        "step": 2090,
        "loss": 1.28
      },
      {
        "step": 2100,
        "loss": 1.2224
      },
      {
        "step": 2110,
        "loss": 1.2025
      },
      {
        "step": 2120,
        "loss": 1.2474
      },
      {
        "step": 2130,
        "loss": 1.2056
      },
      {
        "step": 2140,
        "loss": 1.1869
      },
      {
        "step": 2150,
        "loss": 1.2272
      },
      {
        "step": 2160,
        "loss": 1.2293
      },
      {
        "step": 2170,
        "loss": 1.2471
      },
      {
        "step": 2180,
        "loss": 1.2656
      },
      {
        "step": 2190,
        "loss": 1.2
      },
      {
        "step": 2200,
        "loss": 1.2458
      },
      {
        "step": 2210,
        "loss": 1.2604
      },
      {
        "step": 2220,
        "loss": 1.2675
      },
      {
        "step": 2230,
        "loss": 1.1554
      },
      {
        "step": 2240,
        "loss": 1.2524
      },
      {
        "step": 2250,
        "loss": 1.2281
      },
      {
        "step": 2260,
        "loss": 1.2298
      },
      {
        "step": 2270,
        "loss": 1.201
      },
      {
        "step": 2280,
        "loss": 1.3043
      },
      {
        "step": 2290,
        "loss": 1.2338
      },
      {
        "step": 2300,
        "loss": 1.2259
      },
      {
        "step": 2310,
        "loss": 1.269
      },
      {
        "step": 2320,
        "loss": 1.1879
      },
      {
        "step": 2330,
        "loss": 1.2864
      },
      {
        "step": 2340,
        "loss": 1.1599
      },
      {
        "step": 2350,
        "loss": 1.2573
      },
      {
        "step": 2360,
        "loss": 1.1891
      },
      {
        "step": 2370,
        "loss": 1.1996
      },
      {
        "step": 2380,
        "loss": 1.1881
      },
      {
        "step": 2390,
        "loss": 1.2102
      },
      {
        "step": 2400,
        "loss": 1.231
      },
      {
        "step": 2410,
        "loss": 1.1887
      },
      {
        "step": 2420,
        "loss": 1.2592
      },
      {
        "step": 2430,
        "loss": 1.2463
      },
      {
        "step": 2440,
        "loss": 1.1877
      },
      {
        "step": 2450,
        "loss": 1.1856
      },
      {
        "step": 2460,
        "loss": 1.1651
      },
      {
        "step": 2470,
        "loss": 1.1922
      },
      {
        "step": 2480,
        "loss": 1.2138
      },
      {
        "step": 2490,
        "loss": 1.2177
      },
      {
        "step": 2500,
        "loss": 1.1258
      },
      {
        "step": 2510,
        "loss": 1.2016
      },
      {
        "step": 2520,
        "loss": 1.187
      },
      {
        "step": 2530,
        "loss": 1.1278
      },
      {
        "step": 2540,
        "loss": 1.1326
      },
      {
        "step": 2550,
        "loss": 1.1658
      },
      {
        "step": 2560,
        "loss": 1.2028
      },
      {
        "step": 2570,
        "loss": 1.1745
      },
      {
        "step": 2580,
        "loss": 1.2145
      },
      {
        "step": 2590,
        "loss": 1.1599
      },
      {
        "step": 2600,
        "loss": 1.1821
      },
      {
        "step": 2610,
        "loss": 1.1556
      },
      {
        "step": 2620,
        "loss": 1.1041
      },
      {
        "step": 2630,
        "loss": 1.1113
      },
      {
        "step": 2640,
        "loss": 1.1876
      },
      {
        "step": 2650,
        "loss": 1.1454
      },
      {
        "step": 2660,
        "loss": 1.1553
      },
      {
        "step": 2670,
        "loss": 1.1592
      },
      {
        "step": 2680,
        "loss": 1.0899
      },
      {
        "step": 2690,
        "loss": 1.1161
      },
      {
        "step": 2700,
        "loss": 1.1447
      },
      {
        "step": 2710,
        "loss": 1.1271
      },
      {
        "step": 2720,
        "loss": 1.0805
      },
      {
        "step": 2730,
        "loss": 1.1149
      },
      {
        "step": 2740,
        "loss": 1.1047
      },
      {
        "step": 2750,
        "loss": 1.084
      },
      {
        "step": 2760,
        "loss": 1.0509
      },
      {
        "step": 2770,
        "loss": 1.0734
      },
      {
        "step": 2780,
        "loss": 1.1274
      },
      {
        "step": 2790,
        "loss": 1.1625
      },
      {
        "step": 2800,
        "loss": 1.1676
      },
      {
        "step": 2810,
        "loss": 1.1057
      },
      {
        "step": 2820,
        "loss": 1.1317
      },
      {
        "step": 2830,
        "loss": 1.1213
      },
      {
        "step": 2840,
        "loss": 1.0963
      },
      {
        "step": 2850,
        "loss": 1.0519
      },
      {
        "step": 2860,
        "loss": 1.0437
      },
      {
        "step": 2870,
        "loss": 1.0848
      },
      {
        "step": 2880,
        "loss": 1.0567
      },
      {
        "step": 2890,
        "loss": 1.1334
      },
      {
        "step": 2900,
        "loss": 1.0337
      },
      {
        "step": 2910,
        "loss": 1.0728
      },
      {
        "step": 2920,
        "loss": 1.0315
      },
      {
        "step": 2930,
        "loss": 1.1365
      },
      {
        "step": 2940,
        "loss": 1.0454
      },
      {
        "step": 2950,
        "loss": 1.0562
      },
      {
        "step": 2960,
        "loss": 1.0829
      },
      {
        "step": 2970,
        "loss": 1.0861
      },
      {
        "step": 2980,
        "loss": 1.1122
      },
      {
        "step": 2990,
        "loss": 1.1196
      },
      {
        "step": 3000,
        "loss": 1.0709
      },
      {
        "step": 3010,
        "loss": 0.9935
      },
      {
        "step": 3020,
        "loss": 1.0229
      },
      {
        "step": 3030,
        "loss": 1.0499
      },
      {
        "step": 3040,
        "loss": 1.0309
      },
      {
        "step": 3050,
        "loss": 1.0398
      },
      {
        "step": 3060,
        "loss": 1.0731
      },
      {
        "step": 3070,
        "loss": 1.0117
      },
      {
        "step": 3080,
        "loss": 1.0326
      },
      {
        "step": 3090,
        "loss": 1.0748
      },
      {
        "step": 3100,
        "loss": 1.0716
      },
      {
        "step": 3110,
        "loss": 1.0405
      },
      {
        "step": 3120,
        "loss": 1.0461
      },
      {
        "step": 3130,
        "loss": 1.0684
      },
      {
        "step": 3140,
        "loss": 1.059
      },
      {
        "step": 3150,
        "loss": 1.0927
      },
      {
        "step": 3160,
        "loss": 1.0596
      },
      {
        "step": 3170,
        "loss": 0.9962
      },
      {
        "step": 3180,
        "loss": 1.0275
      },
      {
        "step": 3190,
        "loss": 1.0188
      },
      {
        "step": 3200,
        "loss": 1.0727
      },
      {
        "step": 3210,
        "loss": 1.0658
      },
      {
        "step": 3220,
        "loss": 1.0387
      },
      {
        "step": 3230,
        "loss": 1.0476
      },
      {
        "step": 3240,
        "loss": 1.1062
      },
      {
        "step": 3250,
        "loss": 1.0236
      },
      {
        "step": 3260,
        "loss": 1.055
      },
      {
        "step": 3270,
        "loss": 1.0018
      },
      {
        "step": 3280,
        "loss": 1.0395
      },
      {
        "step": 3290,
        "loss": 1.0091
      },
      {
        "step": 3300,
        "loss": 1.0468
      },
      {
        "step": 3310,
        "loss": 1.027
      },
      {
        "step": 3320,
        "loss": 0.9789
      },
      {
        "step": 3330,
        "loss": 1.0499
      },
      {
        "step": 3340,
        "loss": 1.0766
      },
      {
        "step": 3350,
        "loss": 1.0303
      },
      {
        "step": 3360,
        "loss": 1.0412
      },
      {
        "step": 3370,
        "loss": 1.0523
      },
      {
        "step": 3380,
        "loss": 0.9609
      },
      {
        "step": 3390,
        "loss": 0.9883
      },
      {
        "step": 3400,
        "loss": 1.0179
      },
      {
        "step": 3410,
        "loss": 1.0759
      },
      {
        "step": 3420,
        "loss": 0.979
      },
      {
        "step": 3430,
        "loss": 0.9599
      },
      {
        "step": 3440,
        "loss": 0.9309
      },
      {
        "step": 3450,
        "loss": 0.9493
      },
      {
        "step": 3460,
        "loss": 0.9775
      },
      {
        "step": 3470,
        "loss": 0.948
      },
      {
        "step": 3480,
        "loss": 0.9815
      },
      {
        "step": 3490,
        "loss": 0.9525
      },
      {
        "step": 3500,
        "loss": 0.9415
      },
      {
        "step": 3510,
        "loss": 0.9382
      },
      {
        "step": 3520,
        "loss": 0.9935
      },
      {
        "step": 3530,
        "loss": 1.0066
      },
      {
        "step": 3540,
        "loss": 0.9142
      },
      {
        "step": 3550,
        "loss": 0.9081
      },
      {
        "step": 3560,
        "loss": 0.9366
      },
      {
        "step": 3570,
        "loss": 0.9029
      },
      {
        "step": 3580,
        "loss": 0.9199
      },
      {
        "step": 3590,
        "loss": 0.9736
      },
      {
        "step": 3600,
        "loss": 1.0108
      },
      {
        "step": 3610,
        "loss": 0.9822
      },
      {
        "step": 3620,
        "loss": 0.9726
      },
      {
        "step": 3630,
        "loss": 0.889
      },
      {
        "step": 3640,
        "loss": 0.9031
      },
      {
        "step": 3650,
        "loss": 0.942
      },
      {
        "step": 3660,
        "loss": 0.9331
      },
      {
        "step": 3670,
        "loss": 0.9549
      },
      {
        "step": 3680,
        "loss": 0.9189
      },
      {
        "step": 3690,
        "loss": 0.8943
      },
      {
        "step": 3700,
        "loss": 0.896
      },
      {
        "step": 3710,
        "loss": 0.9396
      },
      {
        "step": 3720,
        "loss": 0.9822
      },
      {
        "step": 3730,
        "loss": 0.906
      },
      {
        "step": 3740,
        "loss": 0.9141
      },
      {
        "step": 3750,
        "loss": 0.9494
      },
      {
        "step": 3760,
        "loss": 0.817
      },
      {
        "step": 3770,
        "loss": 0.9187
      },
      {
        "step": 3780,
        "loss": 0.8647
      },
      {
        "step": 3790,
        "loss": 0.8885
      },
      {
        "step": 3800,
        "loss": 0.8865
      },
      {
        "step": 3810,
        "loss": 0.9352
      },
      {
        "step": 3820,
        "loss": 0.8406
      },
      {
        "step": 3830,
        "loss": 0.9897
      },
      {
        "step": 3840,
        "loss": 0.9049
      },
      {
        "step": 3850,
        "loss": 0.8154
      },
      {
        "step": 3860,
        "loss": 0.8615
      },
      {
        "step": 3870,
        "loss": 0.9102
      },
      {
        "step": 3880,
        "loss": 0.8324
      },
      {
        "step": 3890,
        "loss": 0.7863
      },
      {
        "step": 3900,
        "loss": 0.9035
      },
      {
        "step": 3910,
        "loss": 0.8819
      },
      {
        "step": 3920,
        "loss": 0.851
      },
      {
        "step": 3930,
        "loss": 0.8715
      },
      {
        "step": 3940,
        "loss": 0.8554
      },
      {
        "step": 3950,
        "loss": 0.8402
      },
      {
        "step": 3960,
        "loss": 0.8611
      },
      {
        "step": 3970,
        "loss": 0.9339
      },
      {
        "step": 3980,
        "loss": 0.7965
      },
      {
        "step": 3990,
        "loss": 0.8585
      },
      {
        "step": 4000,
        "loss": 0.9184
      },
      {
        "step": 4010,
        "loss": 0.8813
      },
      {
        "step": 4020,
        "loss": 0.8204
      },
      {
        "step": 4030,
        "loss": 0.8152
      },
      {
        "step": 4040,
        "loss": 0.7684
      },
      {
        "step": 4050,
        "loss": 0.812
      },
      {
        "step": 4060,
        "loss": 0.8728
      },
      {
        "step": 4070,
        "loss": 0.8336
      },
      {
        "step": 4080,
        "loss": 0.8128
      },
      {
        "step": 4090,
        "loss": 0.8502
      },
      {
        "step": 4100,
        "loss": 0.7714
      },
      {
        "step": 4110,
        "loss": 0.8245
      },
      {
        "step": 4120,
        "loss": 0.7632
      },
      {
        "step": 4130,
        "loss": 0.8221
      },
      {
        "step": 4140,
        "loss": 0.8571
      },
      {
        "step": 4150,
        "loss": 0.7722
      },
      {
        "step": 4160,
        "loss": 0.7528
      },
      {
        "step": 4170,
        "loss": 0.7891
      },
      {
        "step": 4180,
        "loss": 0.8159
      },
      {
        "step": 4190,
        "loss": 0.8034
      },
      {
        "step": 4200,
        "loss": 0.8307
      },
      {
        "step": 4210,
        "loss": 0.7843
      },
      {
        "step": 4220,
        "loss": 0.7723
      },
      {
        "step": 4230,
        "loss": 0.7761
      },
      {
        "step": 4240,
        "loss": 0.8488
      },
      {
        "step": 4250,
        "loss": 0.7757
      },
      {
        "step": 4260,
        "loss": 0.7578
      },
      {
        "step": 4270,
        "loss": 0.7713
      },
      {
        "step": 4280,
        "loss": 0.8244
      },
      {
        "step": 4290,
        "loss": 0.8917
      },
      {
        "step": 4300,
        "loss": 0.8613
      },
      {
        "step": 4310,
        "loss": 0.7929
      },
      {
        "step": 4320,
        "loss": 0.7321
      },
      {
        "step": 4330,
        "loss": 0.7743
      },
      {
        "step": 4340,
        "loss": 0.7322
      },
      {
        "step": 4350,
        "loss": 0.8168
      },
      {
        "step": 4360,
        "loss": 0.7011
      },
      {
        "step": 4370,
        "loss": 0.7114
      },
      {
        "step": 4380,
        "loss": 0.8298
      },
      {
        "step": 4390,
        "loss": 0.7303
      },
      {
        "step": 4400,
        "loss": 0.7254
      },
      {
        "step": 4410,
        "loss": 0.6399
      },
      {
        "step": 4420,
        "loss": 0.7771
      },
      {
        "step": 4430,
        "loss": 0.7374
      },
      {
        "step": 4440,
        "loss": 0.7675
      },
      {
        "step": 4450,
        "loss": 0.7627
      },
      {
        "step": 4460,
        "loss": 0.8455
      },
      {
        "step": 4470,
        "loss": 0.7764
      },
      {
        "step": 4480,
        "loss": 0.7551
      },
      {
        "step": 4490,
        "loss": 0.7785
      },
      {
        "step": 4500,
        "loss": 0.7497
      },
      {
        "step": 4510,
        "loss": 0.7066
      },
      {
        "step": 4520,
        "loss": 0.7522
      },
      {
        "step": 4530,
        "loss": 0.8323
      },
      {
        "step": 4540,
        "loss": 0.7549
      },
      {
        "step": 4550,
        "loss": 0.7961
      },
      {
        "step": 4560,
        "loss": 0.7325
      },
      {
        "step": 4570,
        "loss": 0.6986
      },
      {
        "step": 4580,
        "loss": 0.7671
      },
      {
        "step": 4590,
        "loss": 0.707
      },
      {
        "step": 4600,
        "loss": 0.7012
      },
      {
        "step": 4610,
        "loss": 0.7046
      },
      {
        "step": 4620,
        "loss": 0.6974
      },
      {
        "step": 4630,
        "loss": 0.7363
      },
      {
        "step": 4640,
        "loss": 0.7309
      },
      {
        "step": 4650,
        "loss": 0.7151
      },
      {
        "step": 4660,
        "loss": 0.7188
      },
      {
        "step": 4670,
        "loss": 0.7332
      },
      {
        "step": 4680,
        "loss": 0.6617
      },
      {
        "step": 4690,
        "loss": 0.6542
      },
      {
        "step": 4700,
        "loss": 0.7064
      },
      {
        "step": 4710,
        "loss": 0.6498
      },
      {
        "step": 4720,
        "loss": 0.6887
      },
      {
        "step": 4730,
        "loss": 0.7342
      },
      {
        "step": 4740,
        "loss": 0.6452
      },
      {
        "step": 4750,
        "loss": 0.7286
      },
      {
        "step": 4760,
        "loss": 0.7846
      },
      {
        "step": 4770,
        "loss": 0.7066
      },
      {
        "step": 4780,
        "loss": 0.6914
      },
      {
        "step": 4790,
        "loss": 0.7457
      },
      {
        "step": 4800,
        "loss": 0.7211
      },
      {
        "step": 4810,
        "loss": 0.6497
      },
      {
        "step": 4820,
        "loss": 0.7013
      },
      {
        "step": 4830,
        "loss": 0.7284
      },
      {
        "step": 4840,
        "loss": 0.685
      },
      {
        "step": 4850,
        "loss": 0.6605
      },
      {
        "step": 4860,
        "loss": 0.7025
      },
      {
        "step": 4870,
        "loss": 0.7151
      },
      {
        "step": 4880,
        "loss": 0.6256
      },
      {
        "step": 4890,
        "loss": 0.6265
      },
      {
        "step": 4900,
        "loss": 0.6468
      },
      {
        "step": 4910,
        "loss": 0.6062
      },
      {
        "step": 4920,
        "loss": 0.718
      },
      {
        "step": 4930,
        "loss": 0.5818
      },
      {
        "step": 4940,
        "loss": 0.6555
      },
      {
        "step": 4950,
        "loss": 0.611
      },
      {
        "step": 4960,
        "loss": 0.5937
      },
      {
        "step": 4970,
        "loss": 0.6286
      },
      {
        "step": 4980,
        "loss": 0.6304
      },
      {
        "step": 4990,
        "loss": 0.6864
      },
      {
        "step": 5000,
        "loss": 0.5952
      }
    ],
    "evals": [
      {
        "step": 100,
        "loss": 2.5258
      },
      {
        "step": 200,
        "loss": 2.406
      },
      {
        "step": 300,
        "loss": 2.138
      },
      {
        "step": 400,
        "loss": 2.0034
      },
      {
        "step": 500,
        "loss": 1.8895
      },
      {
        "step": 600,
        "loss": 1.8194
      },
      {
        "step": 700,
        "loss": 1.7727
      },
      {
        "step": 800,
        "loss": 1.7211
      },
      {
        "step": 900,
        "loss": 1.7124
      },
      {
        "step": 1000,
        "loss": 1.667
      },
      {
        "step": 1100,
        "loss": 1.6381
      },
      {
        "step": 1200,
        "loss": 1.6306
      },
      {
        "step": 1300,
        "loss": 1.5958
      },
      {
        "step": 1400,
        "loss": 1.5842
      },
      {
        "step": 1500,
        "loss": 1.5836
      },
      {
        "step": 1600,
        "loss": 1.5698
      },
      {
        "step": 1700,
        "loss": 1.5613
      },
      {
        "step": 1800,
        "loss": 1.5268
      },
      {
        "step": 1900,
        "loss": 1.5402
      },
      {
        "step": 2000,
        "loss": 1.5298
      },
      {
        "step": 2100,
        "loss": 1.5224
      },
      {
        "step": 2200,
        "loss": 1.5216
      },
      {
        "step": 2300,
        "loss": 1.5233
      },
      {
        "step": 2400,
        "loss": 1.5035
      },
      {
        "step": 2500,
        "loss": 1.5132
      },
      {
        "step": 2600,
        "loss": 1.5062
      },
      {
        "step": 2700,
        "loss": 1.5203
      },
      {
        "step": 2800,
        "loss": 1.5244
      },
      {
        "step": 2900,
        "loss": 1.5277
      },
      {
        "step": 3000,
        "loss": 1.5339
      },
      {
        "step": 3100,
        "loss": 1.5331
      },
      {
        "step": 3200,
        "loss": 1.551
      },
      {
        "step": 3300,
        "loss": 1.5501
      },
      {
        "step": 3400,
        "loss": 1.5659
      },
      {
        "step": 3500,
        "loss": 1.5918
      },
      {
        "step": 3600,
        "loss": 1.5934
      },
      {
        "step": 3700,
        "loss": 1.6165
      },
      {
        "step": 3800,
        "loss": 1.6372
      },
      {
        "step": 3900,
        "loss": 1.6532
      },
      {
        "step": 4000,
        "loss": 1.6787
      },
      {
        "step": 4100,
        "loss": 1.6972
      },
      {
        "step": 4200,
        "loss": 1.7191
      },
      {
        "step": 4300,
        "loss": 1.7485
      },
      {
        "step": 4400,
        "loss": 1.7857
      },
      {
        "step": 4500,
        "loss": 1.8034
      },
      {
        "step": 4600,
        "loss": 1.8495
      },
      {
        "step": 4700,
        "loss": 1.8786
      },
      {
        "step": 4800,
        "loss": 1.8847
      },
      {
        "step": 4900,
        "loss": 1.9245
      },
      {
        "step": 5000,
        "loss": 1.9647
      }
    ],
    "sample": "Lord Lord Hastings, and that hast the mark liken should.\n\nCAMILLO:\nI quarrel of Ebborn to my sail of usure\nI will part a born of those in Rosaling,\nIs it an art to slike the fairer of this.\n\nLADY ANNE:\nI do so leave throught were my love distress'd floud\nIn this mind a doit truth of victor my black.\n\nLADY CAPULET:\nTrust the might soft soldier, mistrus, it plead,\nThat prisonment it was done: what our reason Leed,\nOur weeking the strange of come to the brief,\nOr, the side of the side one pril a crams.\nWhat is my thoughts the fish of the sun\nOf a bulk in a those of my those motherwise to chide.\n\nKING RICHARD III:\nAnd take my will I am lady to quick and on my life.\nMy protectors, and let me go must I have thee.\n\nDERBY:\nAy, this son a happy and my prayer trial,\nLike an exaction bloody blood terror the hair:\nSorrow of dye it more than my own sweet and chance\nIs that traitor free and the circle's of justice,\nOrge one strived in the wings of it.\n\nKING EDWARD IV:\nBut command on his hands is dea"
  },
  "flash": {
    "shape": {
      "B": 16,
      "T": 256,
      "C": 384,
      "NH": 6
    },
    "fwd": {
      "unfused": {
        "name": "unfused (3 kernels)",
        "ms": 1.13,
        "medMs": 1.138,
        "gflops": 715.1,
        "speedup": 1.0,
        "errs": []
      },
      "best": {
        "name": "br64 bc32 t128 4x4",
        "ms": 0.333,
        "medMs": 0.346,
        "gflops": 2429.2,
        "speedup": 3.4,
        "errs": [
          2.09e-07
        ]
      },
      "configs": [
        {
          "name": "br64 bc64 t128 4x8",
          "ms": 0.446,
          "medMs": 0.449,
          "gflops": 1810.8,
          "speedup": 2.53,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br64 bc32 t128 4x4",
          "ms": 0.333,
          "medMs": 0.346,
          "gflops": 2429.2,
          "speedup": 3.4,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br64 bc64 t256 4x4",
          "ms": 0.355,
          "medMs": 0.357,
          "gflops": 2275.2,
          "speedup": 3.18,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br128 bc32 t256 4x4",
          "ms": 0.424,
          "medMs": 0.426,
          "gflops": 1907.0,
          "speedup": 2.67,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br32 bc32 t64 4x4",
          "ms": 0.391,
          "medMs": 0.397,
          "gflops": 2066.8,
          "speedup": 2.89,
          "errs": [
            2.09e-07
          ]
        }
      ]
    },
    "bwd": {
      "unfused": {
        "name": "unfused (7 kernels)",
        "ms": 1.905,
        "medMs": 1.919,
        "gflops": 1485.6,
        "speedup": 1.0,
        "errs": []
      },
      "best": {
        "name": "br32 bc32 t128 kv4x4 q4x4",
        "ms": 1.597,
        "medMs": 1.623,
        "gflops": 1771.3,
        "speedup": 1.19,
        "errs": [
          3e-07,
          4.19e-07,
          3.26e-07
        ]
      },
      "configs": [
        {
          "name": "br64 bc32 t128 kv4x4 q8x4",
          "ms": 1.783,
          "medMs": 1.793,
          "gflops": 1587.2,
          "speedup": 1.07,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br64 bc32 t128 kv4x4 q4x8",
          "ms": 1.96,
          "medMs": 1.969,
          "gflops": 1443.7,
          "speedup": 0.97,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc32 t64  kv4x8 q4x8",
          "ms": 2.091,
          "medMs": 2.113,
          "gflops": 1353.2,
          "speedup": 0.91,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc32 t64  kv8x4 q8x4",
          "ms": 1.64,
          "medMs": 1.658,
          "gflops": 1724.9,
          "speedup": 1.16,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc32 t128 kv4x4 q4x4",
          "ms": 1.597,
          "medMs": 1.623,
          "gflops": 1771.3,
          "speedup": 1.19,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc64 t128 kv8x4 q4x4",
          "ms": 2.0,
          "medMs": 2.009,
          "gflops": 1414.9,
          "speedup": 0.95,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        }
      ]
    },
    "err": {
      "out": 2.09e-07,
      "dq": 3e-07,
      "dk": 4.19e-07,
      "dv": 3.26e-07
    },
    "savedMbPerLayer": 50.3,
    "memory": [
      {
        "ctx": 256,
        "fused": 0.91,
        "unfused": 1.23
      },
      {
        "ctx": 512,
        "fused": 1.65,
        "unfused": 2.64
      },
      {
        "ctx": 1024,
        "fused": 3.15,
        "unfused": 6.42
      },
      {
        "ctx": 2048,
        "fused": 6.13,
        "unfused": 17.94
      },
      {
        "ctx": 3072,
        "fused": 9.12,
        "unfused": null
      },
      {
        "ctx": 4096,
        "fused": 12.11,
        "unfused": null
      }
    ],
    "profile": [
      {
        "name": "forward",
        "l1": 71.35,
        "dram": 40.32,
        "compute": 38.43,
        "occupancy": 16.11
      },
      {
        "name": "backward dK/dV",
        "l1": 87.67,
        "dram": 23.85,
        "compute": 35.78,
        "occupancy": 16.37
      },
      {
        "name": "backward dQ",
        "l1": 88.22,
        "dram": 21.03,
        "compute": 34.25,
        "occupancy": 16.33
      }
    ]
  }
} as const;
