// GENERATED by tools/make_site_data.py -- do not edit.
// Numbers come from bench/results.csv and bench/logs/train_final.log.

export const data = {
  "kernels": [
    {
      "id": 1,
      "name": "naive",
      "gflops": 82.78,
      "pct": 1.17,
      "note": "one thread per output element, uncoalesced",
      "intensity": 0.25,
      "bySize": {
        "512": 1.68,
        "1024": 1.35,
        "2048": 1.21,
        "4096": 1.17
      }
    },
    {
      "id": 2,
      "name": "coalesced",
      "gflops": 646.56,
      "pct": 9.12,
      "note": "swapped which index maps to threadIdx.x",
      "intensity": 0.25,
      "bySize": {
        "512": 13.21,
        "1024": 11.05,
        "2048": 9.97,
        "4096": 9.12
      }
    },
    {
      "id": 3,
      "name": "smem",
      "gflops": 814.67,
      "pct": 11.49,
      "note": "32x32 shared-memory tile",
      "intensity": 8,
      "bySize": {
        "512": 16.67,
        "1024": 14.04,
        "2048": 12.58,
        "4096": 11.49
      }
    },
    {
      "id": 4,
      "name": "tile1d",
      "gflops": 2579.03,
      "pct": 36.38,
      "note": "8 outputs per thread (TM=8)",
      "intensity": 16,
      "bySize": {
        "512": 48.76,
        "1024": 39.79,
        "2048": 39.03,
        "4096": 36.38
      }
    },
    {
      "id": 5,
      "name": "tile2d",
      "gflops": 5267.36,
      "pct": 74.33,
      "note": "8x8 register tile, outer-product form",
      "intensity": 32,
      "bySize": {
        "512": 38.93,
        "1024": 69.27,
        "2048": 68.04,
        "4096": 74.33
      }
    },
    {
      "id": 6,
      "name": "vectorized",
      "gflops": 6254.62,
      "pct": 88.1,
      "note": "float4 loads + transposed A tile",
      "intensity": 32,
      "bySize": {
        "512": 49.58,
        "1024": 91.1,
        "2048": 83.11,
        "4096": 88.1
      }
    },
    {
      "id": 7,
      "name": "warptile",
      "gflops": 6405.35,
      "pct": 90.2,
      "note": "block -> warp -> thread blocking",
      "intensity": 32,
      "bySize": {
        "512": 47.97,
        "1024": 94.29,
        "2048": 84.32,
        "4096": 90.2
      }
    },
    {
      "id": 8,
      "name": "dbuffer",
      "gflops": 6801.69,
      "pct": 96.0,
      "note": "double-buffered SMEM, one barrier per chunk",
      "intensity": 32,
      "bySize": {
        "512": 49.57,
        "1024": 98.3,
        "2048": 89.34,
        "4096": 96.0
      }
    },
    {
      "id": 9,
      "name": "tensorcore",
      "gflops": 8130.48,
      "pct": 114.51,
      "note": "WMMA m16n16k8 TF32 tensor cores",
      "intensity": 64,
      "bySize": {
        "512": 60.2,
        "1024": 109.4,
        "2048": 104.97,
        "4096": 114.51
      }
    }
  ],
  "tf32": {
    "dbuffer": {
      "1024": {
        "gflops": 5924.16,
        "pct": 65.82,
        "cublasTf32": 9000.65
      },
      "2048": {
        "gflops": 6114.15,
        "pct": 65.31,
        "cublasTf32": 9362.29
      },
      "4096": {
        "gflops": 6776.96,
        "pct": 64.2,
        "cublasTf32": 10555.86
      }
    },
    "tensorcore": {
      "1024": {
        "gflops": 6594.82,
        "pct": 73.58,
        "cublasTf32": 8962.19
      },
      "2048": {
        "gflops": 7191.26,
        "pct": 77.03,
        "cublasTf32": 9336.24
      },
      "4096": {
        "gflops": 8095.16,
        "pct": 76.72,
        "cublasTf32": 10550.88
      }
    }
  },
  "cublas": 7100.34,
  "benchSize": 4096,
  "sizes": [
    512,
    1024,
    2048,
    4096
  ],
  "training": {
    "totalSteps": 5000,
    "bestVal": 1.5056,
    "bestStep": 2400,
    "finalTrain": 0.6484,
    "finalVal": 1.9316,
    "msPerStep": 85.7,
    "tokPerSec": 47814,
    "gflops": 3435,
    "curve": [
      {
        "step": 1,
        "loss": 4.2625
      },
      {
        "step": 10,
        "loss": 3.1103
      },
      {
        "step": 20,
        "loss": 2.743
      },
      {
        "step": 30,
        "loss": 2.6149
      },
      {
        "step": 40,
        "loss": 2.5989
      },
      {
        "step": 50,
        "loss": 2.5336
      },
      {
        "step": 60,
        "loss": 2.5306
      },
      {
        "step": 70,
        "loss": 2.4765
      },
      {
        "step": 80,
        "loss": 2.4957
      },
      {
        "step": 90,
        "loss": 2.5092
      },
      {
        "step": 100,
        "loss": 2.4958
      },
      {
        "step": 110,
        "loss": 2.5246
      },
      {
        "step": 120,
        "loss": 2.4466
      },
      {
        "step": 130,
        "loss": 2.427
      },
      {
        "step": 140,
        "loss": 2.4549
      },
      {
        "step": 150,
        "loss": 2.4166
      },
      {
        "step": 160,
        "loss": 2.4101
      },
      {
        "step": 170,
        "loss": 2.4118
      },
      {
        "step": 180,
        "loss": 2.399
      },
      {
        "step": 190,
        "loss": 2.3878
      },
      {
        "step": 200,
        "loss": 2.3841
      },
      {
        "step": 210,
        "loss": 2.3918
      },
      {
        "step": 220,
        "loss": 2.3115
      },
      {
        "step": 230,
        "loss": 2.2556
      },
      {
        "step": 240,
        "loss": 2.2052
      },
      {
        "step": 250,
        "loss": 2.159
      },
      {
        "step": 260,
        "loss": 2.1199
      },
      {
        "step": 270,
        "loss": 2.1409
      },
      {
        "step": 280,
        "loss": 2.0727
      },
      {
        "step": 290,
        "loss": 2.0876
      },
      {
        "step": 300,
        "loss": 2.0165
      },
      {
        "step": 310,
        "loss": 2.0243
      },
      {
        "step": 320,
        "loss": 2.0351
      },
      {
        "step": 330,
        "loss": 2.0004
      },
      {
        "step": 340,
        "loss": 1.9982
      },
      {
        "step": 350,
        "loss": 1.9099
      },
      {
        "step": 360,
        "loss": 1.8726
      },
      {
        "step": 370,
        "loss": 1.9317
      },
      {
        "step": 380,
        "loss": 1.8603
      },
      {
        "step": 390,
        "loss": 1.8081
      },
      {
        "step": 400,
        "loss": 1.8917
      },
      {
        "step": 410,
        "loss": 1.8081
      },
      {
        "step": 420,
        "loss": 1.8293
      },
      {
        "step": 430,
        "loss": 1.8924
      },
      {
        "step": 440,
        "loss": 1.8353
      },
      {
        "step": 450,
        "loss": 1.8579
      },
      {
        "step": 460,
        "loss": 1.8
      },
      {
        "step": 470,
        "loss": 1.7615
      },
      {
        "step": 480,
        "loss": 1.7971
      },
      {
        "step": 490,
        "loss": 1.6694
      },
      {
        "step": 500,
        "loss": 1.7417
      },
      {
        "step": 510,
        "loss": 1.7144
      },
      {
        "step": 520,
        "loss": 1.6521
      },
      {
        "step": 530,
        "loss": 1.6873
      },
      {
        "step": 540,
        "loss": 1.7604
      },
      {
        "step": 550,
        "loss": 1.6826
      },
      {
        "step": 560,
        "loss": 1.7656
      },
      {
        "step": 570,
        "loss": 1.6685
      },
      {
        "step": 580,
        "loss": 1.6426
      },
      {
        "step": 590,
        "loss": 1.7302
      },
      {
        "step": 600,
        "loss": 1.6536
      },
      {
        "step": 610,
        "loss": 1.6736
      },
      {
        "step": 620,
        "loss": 1.6206
      },
      {
        "step": 630,
        "loss": 1.5664
      },
      {
        "step": 640,
        "loss": 1.6848
      },
      {
        "step": 650,
        "loss": 1.6087
      },
      {
        "step": 660,
        "loss": 1.579
      },
      {
        "step": 670,
        "loss": 1.6356
      },
      {
        "step": 680,
        "loss": 1.6656
      },
      {
        "step": 690,
        "loss": 1.5631
      },
      {
        "step": 700,
        "loss": 1.5875
      },
      {
        "step": 710,
        "loss": 1.5624
      },
      {
        "step": 720,
        "loss": 1.6133
      },
      {
        "step": 730,
        "loss": 1.6216
      },
      {
        "step": 740,
        "loss": 1.5996
      },
      {
        "step": 750,
        "loss": 1.624
      },
      {
        "step": 760,
        "loss": 1.5723
      },
      {
        "step": 770,
        "loss": 1.523
      },
      {
        "step": 780,
        "loss": 1.6299
      },
      {
        "step": 790,
        "loss": 1.5346
      },
      {
        "step": 800,
        "loss": 1.5245
      },
      {
        "step": 810,
        "loss": 1.6005
      },
      {
        "step": 820,
        "loss": 1.5214
      },
      {
        "step": 830,
        "loss": 1.566
      },
      {
        "step": 840,
        "loss": 1.5615
      },
      {
        "step": 850,
        "loss": 1.4958
      },
      {
        "step": 860,
        "loss": 1.4633
      },
      {
        "step": 870,
        "loss": 1.5066
      },
      {
        "step": 880,
        "loss": 1.482
      },
      {
        "step": 890,
        "loss": 1.53
      },
      {
        "step": 900,
        "loss": 1.5131
      },
      {
        "step": 910,
        "loss": 1.514
      },
      {
        "step": 920,
        "loss": 1.5229
      },
      {
        "step": 930,
        "loss": 1.5329
      },
      {
        "step": 940,
        "loss": 1.5043
      },
      {
        "step": 950,
        "loss": 1.5165
      },
      {
        "step": 960,
        "loss": 1.5177
      },
      {
        "step": 970,
        "loss": 1.4918
      },
      {
        "step": 980,
        "loss": 1.4606
      },
      {
        "step": 990,
        "loss": 1.5124
      },
      {
        "step": 1000,
        "loss": 1.5001
      },
      {
        "step": 1010,
        "loss": 1.4876
      },
      {
        "step": 1020,
        "loss": 1.4671
      },
      {
        "step": 1030,
        "loss": 1.5125
      },
      {
        "step": 1040,
        "loss": 1.4651
      },
      {
        "step": 1050,
        "loss": 1.49
      },
      {
        "step": 1060,
        "loss": 1.4097
      },
      {
        "step": 1070,
        "loss": 1.4567
      },
      {
        "step": 1080,
        "loss": 1.4171
      },
      {
        "step": 1090,
        "loss": 1.4872
      },
      {
        "step": 1100,
        "loss": 1.3463
      },
      {
        "step": 1110,
        "loss": 1.3948
      },
      {
        "step": 1120,
        "loss": 1.3774
      },
      {
        "step": 1130,
        "loss": 1.4442
      },
      {
        "step": 1140,
        "loss": 1.4991
      },
      {
        "step": 1150,
        "loss": 1.394
      },
      {
        "step": 1160,
        "loss": 1.4357
      },
      {
        "step": 1170,
        "loss": 1.4077
      },
      {
        "step": 1180,
        "loss": 1.3933
      },
      {
        "step": 1190,
        "loss": 1.4694
      },
      {
        "step": 1200,
        "loss": 1.4059
      },
      {
        "step": 1210,
        "loss": 1.3877
      },
      {
        "step": 1220,
        "loss": 1.3901
      },
      {
        "step": 1230,
        "loss": 1.3527
      },
      {
        "step": 1240,
        "loss": 1.3721
      },
      {
        "step": 1250,
        "loss": 1.3808
      },
      {
        "step": 1260,
        "loss": 1.3823
      },
      {
        "step": 1270,
        "loss": 1.4128
      },
      {
        "step": 1280,
        "loss": 1.3694
      },
      {
        "step": 1290,
        "loss": 1.4055
      },
      {
        "step": 1300,
        "loss": 1.4419
      },
      {
        "step": 1310,
        "loss": 1.3874
      },
      {
        "step": 1320,
        "loss": 1.3671
      },
      {
        "step": 1330,
        "loss": 1.4005
      },
      {
        "step": 1340,
        "loss": 1.4013
      },
      {
        "step": 1350,
        "loss": 1.3966
      },
      {
        "step": 1360,
        "loss": 1.4071
      },
      {
        "step": 1370,
        "loss": 1.4289
      },
      {
        "step": 1380,
        "loss": 1.3539
      },
      {
        "step": 1390,
        "loss": 1.331
      },
      {
        "step": 1400,
        "loss": 1.3782
      },
      {
        "step": 1410,
        "loss": 1.3689
      },
      {
        "step": 1420,
        "loss": 1.395
      },
      {
        "step": 1430,
        "loss": 1.4279
      },
      {
        "step": 1440,
        "loss": 1.3172
      },
      {
        "step": 1450,
        "loss": 1.3335
      },
      {
        "step": 1460,
        "loss": 1.3094
      },
      {
        "step": 1470,
        "loss": 1.3613
      },
      {
        "step": 1480,
        "loss": 1.3783
      },
      {
        "step": 1490,
        "loss": 1.3933
      },
      {
        "step": 1500,
        "loss": 1.3559
      },
      {
        "step": 1510,
        "loss": 1.3331
      },
      {
        "step": 1520,
        "loss": 1.3691
      },
      {
        "step": 1530,
        "loss": 1.2447
      },
      {
        "step": 1540,
        "loss": 1.3581
      },
      {
        "step": 1550,
        "loss": 1.3755
      },
      {
        "step": 1560,
        "loss": 1.3662
      },
      {
        "step": 1570,
        "loss": 1.3246
      },
      {
        "step": 1580,
        "loss": 1.3002
      },
      {
        "step": 1590,
        "loss": 1.3634
      },
      {
        "step": 1600,
        "loss": 1.2989
      },
      {
        "step": 1610,
        "loss": 1.3109
      },
      {
        "step": 1620,
        "loss": 1.2729
      },
      {
        "step": 1630,
        "loss": 1.3424
      },
      {
        "step": 1640,
        "loss": 1.3334
      },
      {
        "step": 1650,
        "loss": 1.353
      },
      {
        "step": 1660,
        "loss": 1.2859
      },
      {
        "step": 1670,
        "loss": 1.3023
      },
      {
        "step": 1680,
        "loss": 1.351
      },
      {
        "step": 1690,
        "loss": 1.2639
      },
      {
        "step": 1700,
        "loss": 1.3547
      },
      {
        "step": 1710,
        "loss": 1.3002
      },
      {
        "step": 1720,
        "loss": 1.3721
      },
      {
        "step": 1730,
        "loss": 1.3838
      },
      {
        "step": 1740,
        "loss": 1.3054
      },
      {
        "step": 1750,
        "loss": 1.2749
      },
      {
        "step": 1760,
        "loss": 1.3123
      },
      {
        "step": 1770,
        "loss": 1.3337
      },
      {
        "step": 1780,
        "loss": 1.3086
      },
      {
        "step": 1790,
        "loss": 1.2541
      },
      {
        "step": 1800,
        "loss": 1.2929
      },
      {
        "step": 1810,
        "loss": 1.2948
      },
      {
        "step": 1820,
        "loss": 1.2741
      },
      {
        "step": 1830,
        "loss": 1.2825
      },
      {
        "step": 1840,
        "loss": 1.3206
      },
      {
        "step": 1850,
        "loss": 1.2699
      },
      {
        "step": 1860,
        "loss": 1.3081
      },
      {
        "step": 1870,
        "loss": 1.2756
      },
      {
        "step": 1880,
        "loss": 1.2594
      },
      {
        "step": 1890,
        "loss": 1.268
      },
      {
        "step": 1900,
        "loss": 1.236
      },
      {
        "step": 1910,
        "loss": 1.2744
      },
      {
        "step": 1920,
        "loss": 1.1814
      },
      {
        "step": 1930,
        "loss": 1.3003
      },
      {
        "step": 1940,
        "loss": 1.2913
      },
      {
        "step": 1950,
        "loss": 1.2233
      },
      {
        "step": 1960,
        "loss": 1.2491
      },
      {
        "step": 1970,
        "loss": 1.311
      },
      {
        "step": 1980,
        "loss": 1.2559
      },
      {
        "step": 1990,
        "loss": 1.2357
      },
      {
        "step": 2000,
        "loss": 1.2427
      },
      {
        "step": 2010,
        "loss": 1.1883
      },
      {
        "step": 2020,
        "loss": 1.2838
      },
      {
        "step": 2030,
        "loss": 1.2643
      },
      {
        "step": 2040,
        "loss": 1.3171
      },
      {
        "step": 2050,
        "loss": 1.2609
      },
      {
        "step": 2060,
        "loss": 1.2568
      },
      {
        "step": 2070,
        "loss": 1.2818
      },
      {
        "step": 2080,
        "loss": 1.2594
      },
      {
        "step": 2090,
        "loss": 1.285
      },
      {
        "step": 2100,
        "loss": 1.2246
      },
      {
        "step": 2110,
        "loss": 1.2003
      },
      {
        "step": 2120,
        "loss": 1.2421
      },
      {
        "step": 2130,
        "loss": 1.2102
      },
      {
        "step": 2140,
        "loss": 1.1739
      },
      {
        "step": 2150,
        "loss": 1.2324
      },
      {
        "step": 2160,
        "loss": 1.2373
      },
      {
        "step": 2170,
        "loss": 1.2481
      },
      {
        "step": 2180,
        "loss": 1.2545
      },
      {
        "step": 2190,
        "loss": 1.2078
      },
      {
        "step": 2200,
        "loss": 1.231
      },
      {
        "step": 2210,
        "loss": 1.2581
      },
      {
        "step": 2220,
        "loss": 1.2653
      },
      {
        "step": 2230,
        "loss": 1.154
      },
      {
        "step": 2240,
        "loss": 1.2457
      },
      {
        "step": 2250,
        "loss": 1.2176
      },
      {
        "step": 2260,
        "loss": 1.2213
      },
      {
        "step": 2270,
        "loss": 1.1914
      },
      {
        "step": 2280,
        "loss": 1.2986
      },
      {
        "step": 2290,
        "loss": 1.2405
      },
      {
        "step": 2300,
        "loss": 1.2374
      },
      {
        "step": 2310,
        "loss": 1.259
      },
      {
        "step": 2320,
        "loss": 1.2005
      },
      {
        "step": 2330,
        "loss": 1.2934
      },
      {
        "step": 2340,
        "loss": 1.1631
      },
      {
        "step": 2350,
        "loss": 1.2534
      },
      {
        "step": 2360,
        "loss": 1.1887
      },
      {
        "step": 2370,
        "loss": 1.1903
      },
      {
        "step": 2380,
        "loss": 1.1904
      },
      {
        "step": 2390,
        "loss": 1.2052
      },
      {
        "step": 2400,
        "loss": 1.2436
      },
      {
        "step": 2410,
        "loss": 1.1847
      },
      {
        "step": 2420,
        "loss": 1.2607
      },
      {
        "step": 2430,
        "loss": 1.2455
      },
      {
        "step": 2440,
        "loss": 1.1834
      },
      {
        "step": 2450,
        "loss": 1.184
      },
      {
        "step": 2460,
        "loss": 1.162
      },
      {
        "step": 2470,
        "loss": 1.1819
      },
      {
        "step": 2480,
        "loss": 1.2044
      },
      {
        "step": 2490,
        "loss": 1.1982
      },
      {
        "step": 2500,
        "loss": 1.1272
      },
      {
        "step": 2510,
        "loss": 1.1927
      },
      {
        "step": 2520,
        "loss": 1.179
      },
      {
        "step": 2530,
        "loss": 1.1239
      },
      {
        "step": 2540,
        "loss": 1.1297
      },
      {
        "step": 2550,
        "loss": 1.1705
      },
      {
        "step": 2560,
        "loss": 1.2048
      },
      {
        "step": 2570,
        "loss": 1.1756
      },
      {
        "step": 2580,
        "loss": 1.2246
      },
      {
        "step": 2590,
        "loss": 1.148
      },
      {
        "step": 2600,
        "loss": 1.1712
      },
      {
        "step": 2610,
        "loss": 1.1717
      },
      {
        "step": 2620,
        "loss": 1.1065
      },
      {
        "step": 2630,
        "loss": 1.1125
      },
      {
        "step": 2640,
        "loss": 1.1814
      },
      {
        "step": 2650,
        "loss": 1.1534
      },
      {
        "step": 2660,
        "loss": 1.1702
      },
      {
        "step": 2670,
        "loss": 1.1705
      },
      {
        "step": 2680,
        "loss": 1.0911
      },
      {
        "step": 2690,
        "loss": 1.1249
      },
      {
        "step": 2700,
        "loss": 1.1347
      },
      {
        "step": 2710,
        "loss": 1.1339
      },
      {
        "step": 2720,
        "loss": 1.0677
      },
      {
        "step": 2730,
        "loss": 1.1198
      },
      {
        "step": 2740,
        "loss": 1.1135
      },
      {
        "step": 2750,
        "loss": 1.079
      },
      {
        "step": 2760,
        "loss": 1.0404
      },
      {
        "step": 2770,
        "loss": 1.076
      },
      {
        "step": 2780,
        "loss": 1.1321
      },
      {
        "step": 2790,
        "loss": 1.1645
      },
      {
        "step": 2800,
        "loss": 1.1625
      },
      {
        "step": 2810,
        "loss": 1.0917
      },
      {
        "step": 2820,
        "loss": 1.1275
      },
      {
        "step": 2830,
        "loss": 1.1133
      },
      {
        "step": 2840,
        "loss": 1.1039
      },
      {
        "step": 2850,
        "loss": 1.0604
      },
      {
        "step": 2860,
        "loss": 1.0455
      },
      {
        "step": 2870,
        "loss": 1.069
      },
      {
        "step": 2880,
        "loss": 1.07
      },
      {
        "step": 2890,
        "loss": 1.144
      },
      {
        "step": 2900,
        "loss": 1.0347
      },
      {
        "step": 2910,
        "loss": 1.0752
      },
      {
        "step": 2920,
        "loss": 1.0272
      },
      {
        "step": 2930,
        "loss": 1.141
      },
      {
        "step": 2940,
        "loss": 1.043
      },
      {
        "step": 2950,
        "loss": 1.0728
      },
      {
        "step": 2960,
        "loss": 1.0842
      },
      {
        "step": 2970,
        "loss": 1.0893
      },
      {
        "step": 2980,
        "loss": 1.1076
      },
      {
        "step": 2990,
        "loss": 1.1034
      },
      {
        "step": 3000,
        "loss": 1.0727
      },
      {
        "step": 3010,
        "loss": 0.9842
      },
      {
        "step": 3020,
        "loss": 1.0227
      },
      {
        "step": 3030,
        "loss": 1.0574
      },
      {
        "step": 3040,
        "loss": 1.035
      },
      {
        "step": 3050,
        "loss": 1.0371
      },
      {
        "step": 3060,
        "loss": 1.0636
      },
      {
        "step": 3070,
        "loss": 1.0084
      },
      {
        "step": 3080,
        "loss": 1.042
      },
      {
        "step": 3090,
        "loss": 1.0732
      },
      {
        "step": 3100,
        "loss": 1.0652
      },
      {
        "step": 3110,
        "loss": 1.0325
      },
      {
        "step": 3120,
        "loss": 1.0402
      },
      {
        "step": 3130,
        "loss": 1.0694
      },
      {
        "step": 3140,
        "loss": 1.0492
      },
      {
        "step": 3150,
        "loss": 1.0899
      },
      {
        "step": 3160,
        "loss": 1.0581
      },
      {
        "step": 3170,
        "loss": 0.9818
      },
      {
        "step": 3180,
        "loss": 1.0272
      },
      {
        "step": 3190,
        "loss": 1.0176
      },
      {
        "step": 3200,
        "loss": 1.0725
      },
      {
        "step": 3210,
        "loss": 1.0531
      },
      {
        "step": 3220,
        "loss": 1.0384
      },
      {
        "step": 3230,
        "loss": 1.0545
      },
      {
        "step": 3240,
        "loss": 1.0911
      },
      {
        "step": 3250,
        "loss": 1.0123
      },
      {
        "step": 3260,
        "loss": 1.0633
      },
      {
        "step": 3270,
        "loss": 1.0059
      },
      {
        "step": 3280,
        "loss": 1.0296
      },
      {
        "step": 3290,
        "loss": 1.0037
      },
      {
        "step": 3300,
        "loss": 1.0477
      },
      {
        "step": 3310,
        "loss": 1.0306
      },
      {
        "step": 3320,
        "loss": 0.9743
      },
      {
        "step": 3330,
        "loss": 1.0499
      },
      {
        "step": 3340,
        "loss": 1.0614
      },
      {
        "step": 3350,
        "loss": 1.0212
      },
      {
        "step": 3360,
        "loss": 1.0294
      },
      {
        "step": 3370,
        "loss": 1.045
      },
      {
        "step": 3380,
        "loss": 0.9539
      },
      {
        "step": 3390,
        "loss": 0.9808
      },
      {
        "step": 3400,
        "loss": 1.0215
      },
      {
        "step": 3410,
        "loss": 1.0815
      },
      {
        "step": 3420,
        "loss": 0.9696
      },
      {
        "step": 3430,
        "loss": 0.953
      },
      {
        "step": 3440,
        "loss": 0.9327
      },
      {
        "step": 3450,
        "loss": 0.94
      },
      {
        "step": 3460,
        "loss": 0.9623
      },
      {
        "step": 3470,
        "loss": 0.9526
      },
      {
        "step": 3480,
        "loss": 0.9807
      },
      {
        "step": 3490,
        "loss": 0.9598
      },
      {
        "step": 3500,
        "loss": 0.9497
      },
      {
        "step": 3510,
        "loss": 0.9252
      },
      {
        "step": 3520,
        "loss": 0.9957
      },
      {
        "step": 3530,
        "loss": 1.0163
      },
      {
        "step": 3540,
        "loss": 0.9026
      },
      {
        "step": 3550,
        "loss": 0.9152
      },
      {
        "step": 3560,
        "loss": 0.945
      },
      {
        "step": 3570,
        "loss": 0.895
      },
      {
        "step": 3580,
        "loss": 0.913
      },
      {
        "step": 3590,
        "loss": 0.9534
      },
      {
        "step": 3600,
        "loss": 1.0009
      },
      {
        "step": 3610,
        "loss": 0.9697
      },
      {
        "step": 3620,
        "loss": 0.9676
      },
      {
        "step": 3630,
        "loss": 0.8936
      },
      {
        "step": 3640,
        "loss": 0.9067
      },
      {
        "step": 3650,
        "loss": 0.9261
      },
      {
        "step": 3660,
        "loss": 0.9241
      },
      {
        "step": 3670,
        "loss": 0.9597
      },
      {
        "step": 3680,
        "loss": 0.9177
      },
      {
        "step": 3690,
        "loss": 0.9024
      },
      {
        "step": 3700,
        "loss": 0.9018
      },
      {
        "step": 3710,
        "loss": 0.9384
      },
      {
        "step": 3720,
        "loss": 0.9661
      },
      {
        "step": 3730,
        "loss": 0.9169
      },
      {
        "step": 3740,
        "loss": 0.9198
      },
      {
        "step": 3750,
        "loss": 0.9569
      },
      {
        "step": 3760,
        "loss": 0.8087
      },
      {
        "step": 3770,
        "loss": 0.9115
      },
      {
        "step": 3780,
        "loss": 0.8639
      },
      {
        "step": 3790,
        "loss": 0.9004
      },
      {
        "step": 3800,
        "loss": 0.8941
      },
      {
        "step": 3810,
        "loss": 0.9144
      },
      {
        "step": 3820,
        "loss": 0.8368
      },
      {
        "step": 3830,
        "loss": 0.9886
      },
      {
        "step": 3840,
        "loss": 0.9216
      },
      {
        "step": 3850,
        "loss": 0.8347
      },
      {
        "step": 3860,
        "loss": 0.8749
      },
      {
        "step": 3870,
        "loss": 0.9035
      },
      {
        "step": 3880,
        "loss": 0.8389
      },
      {
        "step": 3890,
        "loss": 0.7957
      },
      {
        "step": 3900,
        "loss": 0.8793
      },
      {
        "step": 3910,
        "loss": 0.8739
      },
      {
        "step": 3920,
        "loss": 0.8583
      },
      {
        "step": 3930,
        "loss": 0.8721
      },
      {
        "step": 3940,
        "loss": 0.8509
      },
      {
        "step": 3950,
        "loss": 0.8421
      },
      {
        "step": 3960,
        "loss": 0.8979
      },
      {
        "step": 3970,
        "loss": 0.9289
      },
      {
        "step": 3980,
        "loss": 0.7889
      },
      {
        "step": 3990,
        "loss": 0.8463
      },
      {
        "step": 4000,
        "loss": 0.9196
      },
      {
        "step": 4010,
        "loss": 0.8687
      },
      {
        "step": 4020,
        "loss": 0.8177
      },
      {
        "step": 4030,
        "loss": 0.8173
      },
      {
        "step": 4040,
        "loss": 0.7493
      },
      {
        "step": 4050,
        "loss": 0.8177
      },
      {
        "step": 4060,
        "loss": 0.8316
      },
      {
        "step": 4070,
        "loss": 0.8222
      },
      {
        "step": 4080,
        "loss": 0.8121
      },
      {
        "step": 4090,
        "loss": 0.8653
      },
      {
        "step": 4100,
        "loss": 0.7886
      },
      {
        "step": 4110,
        "loss": 0.8299
      },
      {
        "step": 4120,
        "loss": 0.763
      },
      {
        "step": 4130,
        "loss": 0.8097
      },
      {
        "step": 4140,
        "loss": 0.8391
      },
      {
        "step": 4150,
        "loss": 0.7553
      },
      {
        "step": 4160,
        "loss": 0.7442
      },
      {
        "step": 4170,
        "loss": 0.7843
      },
      {
        "step": 4180,
        "loss": 0.8153
      },
      {
        "step": 4190,
        "loss": 0.8182
      },
      {
        "step": 4200,
        "loss": 0.8331
      },
      {
        "step": 4210,
        "loss": 0.7936
      },
      {
        "step": 4220,
        "loss": 0.7415
      },
      {
        "step": 4230,
        "loss": 0.7793
      },
      {
        "step": 4240,
        "loss": 0.8442
      },
      {
        "step": 4250,
        "loss": 0.7867
      },
      {
        "step": 4260,
        "loss": 0.751
      },
      {
        "step": 4270,
        "loss": 0.7841
      },
      {
        "step": 4280,
        "loss": 0.8132
      },
      {
        "step": 4290,
        "loss": 0.8892
      },
      {
        "step": 4300,
        "loss": 0.8562
      },
      {
        "step": 4310,
        "loss": 0.7766
      },
      {
        "step": 4320,
        "loss": 0.7373
      },
      {
        "step": 4330,
        "loss": 0.7751
      },
      {
        "step": 4340,
        "loss": 0.7201
      },
      {
        "step": 4350,
        "loss": 0.7994
      },
      {
        "step": 4360,
        "loss": 0.6948
      },
      {
        "step": 4370,
        "loss": 0.725
      },
      {
        "step": 4380,
        "loss": 0.8418
      },
      {
        "step": 4390,
        "loss": 0.7291
      },
      {
        "step": 4400,
        "loss": 0.7159
      },
      {
        "step": 4410,
        "loss": 0.6417
      },
      {
        "step": 4420,
        "loss": 0.7688
      },
      {
        "step": 4430,
        "loss": 0.7418
      },
      {
        "step": 4440,
        "loss": 0.7831
      },
      {
        "step": 4450,
        "loss": 0.7656
      },
      {
        "step": 4460,
        "loss": 0.8463
      },
      {
        "step": 4470,
        "loss": 0.7917
      },
      {
        "step": 4480,
        "loss": 0.7449
      },
      {
        "step": 4490,
        "loss": 0.7827
      },
      {
        "step": 4500,
        "loss": 0.767
      },
      {
        "step": 4510,
        "loss": 0.7119
      },
      {
        "step": 4520,
        "loss": 0.7443
      },
      {
        "step": 4530,
        "loss": 0.8045
      },
      {
        "step": 4540,
        "loss": 0.7536
      },
      {
        "step": 4550,
        "loss": 0.7832
      },
      {
        "step": 4560,
        "loss": 0.7169
      },
      {
        "step": 4570,
        "loss": 0.6946
      },
      {
        "step": 4580,
        "loss": 0.7725
      },
      {
        "step": 4590,
        "loss": 0.717
      },
      {
        "step": 4600,
        "loss": 0.693
      },
      {
        "step": 4610,
        "loss": 0.7145
      },
      {
        "step": 4620,
        "loss": 0.7152
      },
      {
        "step": 4630,
        "loss": 0.715
      },
      {
        "step": 4640,
        "loss": 0.7234
      },
      {
        "step": 4650,
        "loss": 0.7183
      },
      {
        "step": 4660,
        "loss": 0.7282
      },
      {
        "step": 4670,
        "loss": 0.7366
      },
      {
        "step": 4680,
        "loss": 0.6558
      },
      {
        "step": 4690,
        "loss": 0.6505
      },
      {
        "step": 4700,
        "loss": 0.7137
      },
      {
        "step": 4710,
        "loss": 0.6468
      },
      {
        "step": 4720,
        "loss": 0.6746
      },
      {
        "step": 4730,
        "loss": 0.727
      },
      {
        "step": 4740,
        "loss": 0.6441
      },
      {
        "step": 4750,
        "loss": 0.7357
      },
      {
        "step": 4760,
        "loss": 0.8073
      },
      {
        "step": 4770,
        "loss": 0.7265
      },
      {
        "step": 4780,
        "loss": 0.6872
      },
      {
        "step": 4790,
        "loss": 0.7409
      },
      {
        "step": 4800,
        "loss": 0.6928
      },
      {
        "step": 4810,
        "loss": 0.6371
      },
      {
        "step": 4820,
        "loss": 0.6964
      },
      {
        "step": 4830,
        "loss": 0.7229
      },
      {
        "step": 4840,
        "loss": 0.6619
      },
      {
        "step": 4850,
        "loss": 0.66
      },
      {
        "step": 4860,
        "loss": 0.6688
      },
      {
        "step": 4870,
        "loss": 0.6985
      },
      {
        "step": 4880,
        "loss": 0.6256
      },
      {
        "step": 4890,
        "loss": 0.6335
      },
      {
        "step": 4900,
        "loss": 0.6517
      },
      {
        "step": 4910,
        "loss": 0.6179
      },
      {
        "step": 4920,
        "loss": 0.7263
      },
      {
        "step": 4930,
        "loss": 0.5794
      },
      {
        "step": 4940,
        "loss": 0.6492
      },
      {
        "step": 4950,
        "loss": 0.6405
      },
      {
        "step": 4960,
        "loss": 0.6036
      },
      {
        "step": 4970,
        "loss": 0.6222
      },
      {
        "step": 4980,
        "loss": 0.6352
      },
      {
        "step": 4990,
        "loss": 0.7008
      },
      {
        "step": 5000,
        "loss": 0.5905
      }
    ],
    "evals": [
      {
        "step": 100,
        "loss": 2.5258
      },
      {
        "step": 200,
        "loss": 2.406
      },
      {
        "step": 300,
        "loss": 2.1374
      },
      {
        "step": 400,
        "loss": 1.9905
      },
      {
        "step": 500,
        "loss": 1.8961
      },
      {
        "step": 600,
        "loss": 1.8305
      },
      {
        "step": 700,
        "loss": 1.779
      },
      {
        "step": 800,
        "loss": 1.7306
      },
      {
        "step": 900,
        "loss": 1.7079
      },
      {
        "step": 1000,
        "loss": 1.6762
      },
      {
        "step": 1100,
        "loss": 1.6409
      },
      {
        "step": 1200,
        "loss": 1.6383
      },
      {
        "step": 1300,
        "loss": 1.6034
      },
      {
        "step": 1400,
        "loss": 1.5939
      },
      {
        "step": 1500,
        "loss": 1.5863
      },
      {
        "step": 1600,
        "loss": 1.5737
      },
      {
        "step": 1700,
        "loss": 1.557
      },
      {
        "step": 1800,
        "loss": 1.5408
      },
      {
        "step": 1900,
        "loss": 1.5342
      },
      {
        "step": 2000,
        "loss": 1.5328
      },
      {
        "step": 2100,
        "loss": 1.5276
      },
      {
        "step": 2200,
        "loss": 1.5259
      },
      {
        "step": 2300,
        "loss": 1.5237
      },
      {
        "step": 2400,
        "loss": 1.5056
      },
      {
        "step": 2500,
        "loss": 1.5089
      },
      {
        "step": 2600,
        "loss": 1.5128
      },
      {
        "step": 2700,
        "loss": 1.513
      },
      {
        "step": 2800,
        "loss": 1.5286
      },
      {
        "step": 2900,
        "loss": 1.5209
      },
      {
        "step": 3000,
        "loss": 1.5346
      },
      {
        "step": 3100,
        "loss": 1.5267
      },
      {
        "step": 3200,
        "loss": 1.5531
      },
      {
        "step": 3300,
        "loss": 1.5526
      },
      {
        "step": 3400,
        "loss": 1.5829
      },
      {
        "step": 3500,
        "loss": 1.5931
      },
      {
        "step": 3600,
        "loss": 1.5903
      },
      {
        "step": 3700,
        "loss": 1.6157
      },
      {
        "step": 3800,
        "loss": 1.6387
      },
      {
        "step": 3900,
        "loss": 1.6509
      },
      {
        "step": 4000,
        "loss": 1.6748
      },
      {
        "step": 4100,
        "loss": 1.6962
      },
      {
        "step": 4200,
        "loss": 1.7141
      },
      {
        "step": 4300,
        "loss": 1.7445
      },
      {
        "step": 4400,
        "loss": 1.7682
      },
      {
        "step": 4500,
        "loss": 1.805
      },
      {
        "step": 4600,
        "loss": 1.8365
      },
      {
        "step": 4700,
        "loss": 1.851
      },
      {
        "step": 4800,
        "loss": 1.8664
      },
      {
        "step": 4900,
        "loss": 1.9079
      },
      {
        "step": 5000,
        "loss": 1.9317
      }
    ],
    "sample": "Lord Lord Amaculled and that handled him,\nAnd cummon and be at the envious story\nAnd this love and her with his sake, he be bequired\nThe matter curren'd the broke of the wars\nI' the should have been much by the destroyms:\nAnd, upon my son's wonding adreadful strange,\nAnd is truth on the still ae in a suffice.\nAnd is't my particular shall have me to the queen,\nAnd have them the child the father soul.\nThat you have these words in the state parley,\nNow this plignity night proclaim'd like one,\nFaining, as I cannot them a verdicious pities,\nWhen see you have the signal breal for a curse\nTo bed the plant of Polixenes\nOf sad not yet me after your living fortune,\nShall they with their recompen and reed\nOn so much she conceals out my pleasured of youth:\nAnd love makes my sorrow in heavens blesses\nWhich I can but succeed a yearth of their honour,\nYou pardon it in the blest from his land,\nShall haste that he or elsome prisoner like.\nO, what is he in this better I laid his scried\nThe recort of he"
  },
  "flash": {
    "shape": {
      "B": 16,
      "T": 256,
      "C": 384,
      "NH": 6
    },
    "fwd": {
      "unfused": {
        "name": "unfused (3 kernels)",
        "ms": 1.133,
        "medMs": 1.138,
        "gflops": 713.8,
        "speedup": 1.0,
        "errs": []
      },
      "best": {
        "name": "br64 bc32 t128 4x4",
        "ms": 0.339,
        "medMs": 0.348,
        "gflops": 2385.2,
        "speedup": 3.34,
        "errs": [
          2.09e-07
        ]
      },
      "configs": [
        {
          "name": "br64 bc64 t128 4x8",
          "ms": 0.456,
          "medMs": 0.461,
          "gflops": 1774.2,
          "speedup": 2.49,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br64 bc32 t128 4x4",
          "ms": 0.339,
          "medMs": 0.348,
          "gflops": 2385.2,
          "speedup": 3.34,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br64 bc64 t256 4x4",
          "ms": 0.356,
          "medMs": 0.361,
          "gflops": 2268.7,
          "speedup": 3.18,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br128 bc32 t256 4x4",
          "ms": 0.423,
          "medMs": 0.428,
          "gflops": 1911.6,
          "speedup": 2.68,
          "errs": [
            2.09e-07
          ]
        },
        {
          "name": "br32 bc32 t64 4x4",
          "ms": 0.381,
          "medMs": 0.39,
          "gflops": 2122.3,
          "speedup": 2.97,
          "errs": [
            2.09e-07
          ]
        }
      ]
    },
    "bwd": {
      "unfused": {
        "name": "unfused (7 kernels)",
        "ms": 1.832,
        "medMs": 1.861,
        "gflops": 1544.6,
        "speedup": 1.0,
        "errs": []
      },
      "best": {
        "name": "br32 bc32 t128 kv4x4 q4x4",
        "ms": 1.602,
        "medMs": 1.628,
        "gflops": 1766.8,
        "speedup": 1.14,
        "errs": [
          3e-07,
          4.19e-07,
          3.26e-07
        ]
      },
      "configs": [
        {
          "name": "br64 bc32 t128 kv4x4 q8x4",
          "ms": 1.763,
          "medMs": 1.773,
          "gflops": 1604.7,
          "speedup": 1.04,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br64 bc32 t128 kv4x4 q4x8",
          "ms": 1.96,
          "medMs": 1.972,
          "gflops": 1443.7,
          "speedup": 0.93,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc32 t64  kv4x8 q4x8",
          "ms": 2.079,
          "medMs": 2.102,
          "gflops": 1361.2,
          "speedup": 0.88,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc32 t64  kv8x4 q8x4",
          "ms": 1.64,
          "medMs": 1.66,
          "gflops": 1724.9,
          "speedup": 1.12,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc32 t128 kv4x4 q4x4",
          "ms": 1.602,
          "medMs": 1.628,
          "gflops": 1766.8,
          "speedup": 1.14,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        },
        {
          "name": "br32 bc64 t128 kv8x4 q4x4",
          "ms": 2.004,
          "medMs": 2.016,
          "gflops": 1412.0,
          "speedup": 0.91,
          "errs": [
            3e-07,
            4.19e-07,
            3.26e-07
          ]
        }
      ]
    },
    "err": {
      "out": 2.09e-07,
      "dq": 3e-07,
      "dk": 4.19e-07,
      "dv": 3.26e-07
    },
    "savedMbPerLayer": 50.3,
    "memory": [
      {
        "ctx": 256,
        "fused": 0.91,
        "unfused": 1.23
      },
      {
        "ctx": 512,
        "fused": 1.65,
        "unfused": 2.64
      },
      {
        "ctx": 1024,
        "fused": 3.15,
        "unfused": 6.42
      },
      {
        "ctx": 2048,
        "fused": 6.13,
        "unfused": 17.94
      },
      {
        "ctx": 3072,
        "fused": 9.12,
        "unfused": null
      },
      {
        "ctx": 4096,
        "fused": 12.11,
        "unfused": null
      }
    ],
    "profile": [
      {
        "name": "forward",
        "l1": 70.37,
        "dram": 40.51,
        "compute": 38.98,
        "occupancy": 16.02
      },
      {
        "name": "backward dK/dV",
        "l1": 71.05,
        "dram": 20.94,
        "compute": 26.29,
        "occupancy": 8.16
      },
      {
        "name": "backward dQ",
        "l1": 66.9,
        "dram": 23.38,
        "compute": 25.12,
        "occupancy": 8.17
      }
    ]
  }
} as const;
